refactor: init.ts周りのeslintエラーと型の修正
misskey-dev/misskey pull request #10157
Opened 2023-03-01 10:47 UTC by KokiSakano

# What
- `/packages/frontend/src/init.ts`ファイルの型修正とeslint修正
- `config.ts`と`local-storage.ts`も修正(エラーの原因だと思って最初に修正してしまいました)

# Why
misskeyの型安全性を保った状態で開発を進められるようにするため

# Additional info (optional)
`document.documentElement`に定義する`lang`はこれまで`null`の時`lang="null"`となっていましたが、nullには意味がないため何も設定しないようにしました(空文字列は別の意味を持つため指定しませんでした)。
> The lang attribute (in no namespace) specifies the primary language for the element's contents and for any of the element's attributes that contain text. Its value must be a valid BCP 47 language tag, or the empty string. Setting the attribute to the empty string indicates that the primary language is unknown. [[BCP47]](https://html.spec.whatwg.org/multipage/references.html#refsBCP47)

https://html.spec.whatwg.org/multipage/dom.html#attr-lang

vueファイルを解釈できずにエラーが出ていたので`/packages/frontend/src/types/vue-shim.d.ts`に型定義をしました。

開発環境でのみ`window`に特別なメソッドを持たせているので、本番の`window`からも間違って扱わないように`window`型の拡張ではなく、eslintの設定で一部anyを許容することで対応しました。

2023-03-05 10:35 UTC, syuilo commented on packages/frontend/src/init.ts
> +if (lang) {
langがnullになることはないはず？

2023-03-05 10:35 UTC, syuilo commented on packages/frontend/src/init.ts
> +//#endregion
マイグレーションもう消しても良さそう

2023-03-06 06:48 UTC, KokiSakano commented on packages/frontend/src/init.ts
> +if (lang) {
@syuilo 
`window.localStorage.getItem`の戻り値が`string | null`なので、型として`null`であることを考慮する必要がありそうです。
空文字列など何らかの初期値をセットするようにしますか？

2023-03-06 06:50 UTC, KokiSakano commented on packages/frontend/src/init.ts
> +//#endregion
@syuilo 
このPRで消して問題ないですか？

2023-03-09 15:30 UTC, tamaina approved these changes

2023-03-09 15:30 UTC, tamaina commented
- config.langをen-USにフォールバックしてみた
- accountのマイグレーションは削除

2023-03-09 16:22 UTC, saschanaz requested changes

2023-03-09 16:22 UTC, saschanaz commented on packages/frontend/src/types/vue-shim.d.ts
> +declare module '*.vue' {
これはダメな気がします。

vscodeでvueのimportエラーが出る場合[Vue Language Features](https://marketplace.visualstudio.com/items?itemName=Vue.volar)を設置してください。

2023-03-17 09:43 UTC, saschanaz approved these changes
👍

2023-03-17 09:46 UTC, KokiSakano commented on packages/frontend/src/types/vue-shim.d.ts
> +declare module '*.vue' {
指摘ありがとうございます。削除しました。
VSCodeの環境が原因でimportエラーが出ているってことですかね？
Vue Language Featuresは入れてましたが、エラーが出ているので設定の修正を試みてみます。

2023-04-05 01:56 UTC, KokiSakano commented
TypeScriptのバージョン5.0.2と@micorsoft/api-extractorのbundled compilerとバージョン合わないエラーなのでこのPRとは関係なさそうですかね＞

2023-04-13 09:46 UTC, tamaina commented
関係ないはず

2023-04-13 09:47 UTC, merged

2023-04-13 09:47 UTC, tamaina commented
👍