Server rules
misskey-dev/misskey pull request #10660
Opened 2023-04-17 07:18 UTC by syuilo

Based on https://github.com/misskey-dev/misskey/pull/10633

2023-04-17 07:52 UTC, EbiseLutica submitted a review, later dismissed

2023-04-17 08:23 UTC, acid-chicken requested changes

2023-04-17 08:23 UTC, acid-chicken commented on packages/frontend/src/components/MkSignupServerRules.vue
> +	return agreeServerRules.value && agreeTos.value && agreeNote.value;
いずれかの項目が存在しない場合どうやっても `agreed` が `true` にならない

2023-04-17 08:24 UTC, syuilo commented on packages/frontend/src/components/MkSignupServerRules.vue
> +	return agreeServerRules.value && agreeTos.value && agreeNote.value;
🙏🙏🙏🙏🙏

2023-04-17 08:24 UTC, acid-chicken commented on packages/frontend/src/components/MkSignupServerRules.vue
> +	return agreeServerRules.value && agreeTos.value && agreeNote.value;
https://6428f7d7b962f0b79f97d6e4-hbjbwpaaef.chromatic.com/?path=/story/components-mksignupserverrules--default

2023-04-17 08:26 UTC, EbiseLutica reviewed
Approveしちゃったけど動作確認もしたいのでmergeは待ってくれるとありがたい

2023-04-17 09:16 UTC, acid-chicken commented on packages/frontend/src/components/MkSignupServerRules.vue
> +	return agreeServerRules.value && agreeTos.value && agreeNote.value;
99fb538de362c4fa277ff97823b7c32bc9ebe2b7
![](https://user-images.githubusercontent.com/20679825/232440877-c9076eab-8f10-4933-911b-2803cea9d93b.png)

2023-04-17 09:51 UTC, syuilo commented on packages/frontend/src/components/MkSignupServerRules.vue
> +	return agreeServerRules.value && agreeTos.value && agreeNote.value;
直した

2023-04-17 09:58 UTC, acid-chicken commented on packages/frontend/src/components/MkSignupServerRules.vue
> +	return agreeServerRules.value && agreeTos.value && agreeNote.value;
[![](https://user-images.githubusercontent.com/20679825/232451877-4ede7b5b-00e8-4f94-a806-43c81951efab.png)](https://www.chromatic.com/build?appId=6428f7d7b962f0b79f97d6e4&number=261)

2023-04-17 10:30 UTC, EbiseLutica commented on packages/frontend/src/pages/admin/server-rules.vue
> +	color: var(--fgOnAccent);
コンパネの方も accentedBg + accent にしたい
```suggestion
	background-color: var(--accentedBg);
	color: var(--accent);
```
<img width="465" alt="image" src="https://user-images.githubusercontent.com/7106976/232459144-383c4c2f-f534-4419-9b54-94829d14420c.png">

2023-04-17 10:51 UTC, acid-chicken commented
（https://github.com/misskey-dev/misskey/pull/10660#pullrequestreview-1387524898 みたいなケースがあるので可能ならストーリーがあると嬉しい）

2023-04-17 15:27 UTC, EbiseLutica approved these changes

2023-04-19 02:01 UTC, syuilo commented
> （[#10660 (review)](https://github.com/misskey-dev/misskey/pull/10660#pullrequestreview-1387524898) みたいなケースがあるので可能ならストーリーがあると嬉しい）

Pull Request Templateに書いとくか

2023-04-19 02:05 UTC, syuilo commented
e2eテストが落ちているけどこれはテストが走る前の段階でエラーになってそう

2023-04-19 02:13 UTC, syuilo commented
vitestも落ちておる
`matchMedia is not defined`
このPRと関係ある？

2023-04-19 02:15 UTC, tamaina commented
e2e #10644

2023-04-19 02:15 UTC, remador commented
No thanks!

Em ter., 18 de abr. de 2023 23:14, syuilo ***@***.***>
escreveu:

> vitestも落ちておる
> matchMedia is not defined
> このPRと関係ある？
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/misskey-dev/misskey/pull/10660#issuecomment-1514036555>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5T3RMUB33JGBKWHHOTOVR3XB5C7FANCNFSM6AAAAAAXAYQKYU>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-04-19 02:18 UTC, tamaina commented
> このPRと関係ある？

ない（前からちょくちょく発生している）

2023-04-19 04:27 UTC, syuilo commented
e2eテスト自体は動くようになったけどサインアップ前にルール確認のステップが入るようになった影響で結局テストは落ちるわね

2023-04-19 04:36 UTC, syuilo commented
あれやっぱりe2eが走らない
確率的なのか

2023-04-19 08:09 UTC, syuilo commented
- 長いルールで折り返されないのを修正
- 番号をstickyに

![a](https://user-images.githubusercontent.com/4439005/233010893-19a53644-a9ff-4016-b6f4-cc97b63ae0d2.gif)

2023-04-19 08:11 UTC, syuilo commented
e2eテストが走らない問題をどうにかしないとどうにもならん

2023-04-19 09:59 UTC, syuilo commented
やっと走ったけどまだ落ちてる
![image](https://user-images.githubusercontent.com/4439005/233040157-9cc4a7e5-89a5-48ca-b948-200bd5227dfa.png)

2023-04-19 10:00 UTC, syuilo commented
`MkSwitch`コンポーネント自体を`click`してもスイッチがオンにはならない可能性があるな

2023-04-19 10:01 UTC, syuilo commented
こういう場合どうしたらいいんだ

2023-04-19 10:02 UTC, syuilo commented
MkFolderも同様の問題がありそう

2023-04-19 10:03 UTC, syuilo commented
これでどうだ

2023-04-19 12:24 UTC, syuilo commented
おー通った

2023-04-19 12:24 UTC, merged

2023-04-19 12:24 UTC, syuilo commented
🙏🙏🙏

2023-07-26 04:43 UTC, tamaina commented
なんでMkModalのスクロールをなくしたのかなと思ったけど結局MkModalの内側でスクロールすべきという話になったのかしら

2023-07-26 04:46 UTC, tamaina commented
復活させたらそれはそれで動かないものが出てくる？

2023-07-26 04:47 UTC, tamaina commented
memo

https://github.com/misskey-dev/misskey/pull/10660/commits/c847381ab7682fa7daeb1e68b8d7a1ef71a77929

2023-07-26 04:47 UTC, syuilo commented
> MkModalの内側でスクロールすべき

だった気がするけどよく覚えてない

> 復活させたらそれはそれで動かないものが出てくる？

復活させても特に問題なかったから復活させる