cwにセンシティブが効いてない
misskey-dev/misskey pull request #10688
Opened 2023-04-22 06:03 UTC by nenohi

## What

CWにてセンシティブワードが含まれていた場合にホーム投稿とします。
## Why

注釈を悪用するユーザーが懸念されるため
## Additional info (optional)

ローカルにてテスト済み
## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2023-04-22 07:07 UTC, syuilo commented on packages/backend/src/core/NoteCreateService.ts
> +			} else if ((data.cw != null) && (await this.metaService.fetch()).sensitiveWords.some(w => data.cw!.includes(w))) {
二回fetchが走るのは無駄感ある

2023-04-22 14:04 UTC, nenohi commented on packages/backend/src/core/NoteCreateService.ts
> +			} else if ((data.cw != null) && (await this.metaService.fetch()).sensitiveWords.some(w => data.cw!.includes(w))) {
this.metaService.fetch()).sensitiveWords.some(w => {return data.text!.includes(w)) || data.cw!includes(w)})
 みたいな書き方できるんだっけ

2023-04-22 14:30 UTC, nenohi commented on packages/backend/src/core/NoteCreateService.ts
> +			} else if ((data.cw != null) && (await this.metaService.fetch()).sensitiveWords.some(w => data.cw!.includes(w))) {
あーちょっと変更します。

CWあり、NGワード：パブリック
CWなし、NGワード：ホーム投稿
CWあり、CWにNGワード：ホーム投稿
とするべきだと思うのですが、多分これで良いと思います

2023-04-22 14:36 UTC, nenohi commented
ちょっと正規表現のテストもしたい

2023-04-22 15:41 UTC, nenohi commented
正規表現めんどくさいかも、とりあえずこれでよさそう
（うんこがセンシティブワードに登録されている場合下記）
![image](https://user-images.githubusercontent.com/18223268/233793767-2afaf3f5-20d2-4e6b-b74a-85baa781dd78.png)

2023-04-22 15:42 UTC, nenohi commented on packages/backend/src/core/NoteCreateService.ts
> +			} else if ((data.cw != null) && (await this.metaService.fetch()).sensitiveWords.some(w => data.cw!.includes(w))) {
2回走らないようにしたかも（cwあるかないかで分岐されてるため

2023-04-24 03:00 UTC, nenohi commented
`/test/g`にも対応したい

2023-04-24 03:06 UTC, nenohi commented
対応した
![image](https://user-images.githubusercontent.com/18223268/233891294-5f056f10-1a40-4416-aeab-c6b747251ef8.png)

2023-04-24 03:23 UTC, nenohi commented
なんかテスト通らなくなったかも？

2023-04-24 04:09 UTC, nenohi commented
#10701 これもクローズできるかも？（問題なければ

2023-04-24 04:26 UTC, syuilo commented
正規表現要る？

2023-04-24 04:29 UTC, u1-liquid commented
少なくともワードバウンダリ（\b）はほしいかも

2023-04-24 04:30 UTC, acid-chicken commented
まんま ReDoS になりそう

2023-04-24 04:35 UTC, nenohi commented
ReDOSのこと考えてなかったかも

2023-04-24 04:37 UTC, nenohi commented
オプションにする？

2023-04-24 04:43 UTC, nenohi commented
これにすれば/test/系のみが正規表現になって良さそう？

2023-04-24 07:52 UTC, nenohi commented
> 正規表現要る？

１つの単語じゃなく、２つの単語が含まれていた場合とかで必要かも

2023-04-24 10:58 UTC, yuriha-chan commented
CWで隠された内容がセンシティブであるのにも関わらず、それ以外の理由でCWにしているという誤解を与えるような投稿をしていることを懸念しているのであれば、「（※この投稿はセンシティブな語句を含んでいます）」などの文言を注釈に自動で挿入すれば事足りると思われるのですがどうでしょうか。

2023-04-24 12:03 UTC, nenohi commented
CWに関して懸念しているものはCWを付けているにも関わらず注釈にてセンシティブな語句が含まれていた場合にホームに投稿されないという事象があります。
これはバグに値すると思っています

2023-04-24 12:11 UTC, yuriha-chan commented
なるほど理解しました。
ありがとうございます。

2023-04-24 23:47 UTC, acid-chicken requested changes

2023-04-24 23:47 UTC, acid-chicken commented on packages/backend/src/core/NoteCreateService.ts
> +					const matchRegex = /\/(.*)\/(.*)/g.exec(w);
- グローバルマッチである意味が分からない
- フラグを触れるようにする必要性が分からない
  - `/path/to/spammers/file` みたいな表現まで正規表現扱いになってしまうので、厳密にパースしないなら `/` で括る以上はやりたくない

2023-04-24 23:47 UTC, acid-chicken commented on packages/backend/src/core/NoteCreateService.ts
> +						return regex.test(data.text!);
正規表現が invalid になったら投稿できなくなりそう

2023-04-24 23:47 UTC, acid-chicken commented on packages/backend/src/core/NoteCreateService.ts
> +				return data.cw!.includes(w);
メソッド全体が長くなっているので、単調でないロジックは繰り返さないで切り出して欲しい

2023-04-24 23:47 UTC, acid-chicken commented on packages/backend/src/core/NoteCreateService.ts
> +			} else if ((data.cw != null) && (await this.metaService.fetch()).sensitiveWords.some(w => {
fetchMeta を繰り返しているのでまとめてほしい

2023-04-25 01:03 UTC, nenohi commented on packages/backend/src/core/NoteCreateService.ts
> +					const matchRegex = /\/(.*)\/(.*)/g.exec(w);
> グローバルマッチである意味が分からない

ここに関してはそれはそう感あった

> フラグを触れるようにする必要性が分からない

フラグに関して考慮しようと思ったのはセンシティブな英単語の登録時に大文字小文字を区別する場合等を考えてたため

> /path/to/spammers/file みたいな表現まで正規表現扱いになってしまうので、厳密にパースしないなら / で括る以上はやりたくない

フラグを考慮しないのであれば//で囲われた場合のみにしたほうがいいため修正

2023-04-25 01:08 UTC, nenohi commented on packages/backend/src/core/NoteCreateService.ts
> +			} else if ((data.cw != null) && (await this.metaService.fetch()).sensitiveWords.some(w => {
data.cwのある無しでどのみち通るのでまとめてみた
間違ってたらすいません！

2023-04-25 01:09 UTC, nenohi commented on packages/backend/src/core/NoteCreateService.ts
> +				return data.cw!.includes(w);
`@bindThis`に関しては必要ですか！？

2023-04-25 01:10 UTC, nenohi commented on packages/backend/src/core/NoteCreateService.ts
> +						return regex.test(data.text!);
patternがあるかどうかのチェックをするようにしました(そもそもpatternに入れずにmatchRegexpから見たほうがいいのでは説で変更

2023-04-25 01:31 UTC, acid-chicken commented on packages/backend/src/core/NoteCreateService.ts
> +						return regex.test(data.text!);
そういうことではなく構文エラーの想定がないという話（`/(/` とでも指定しようものなら何もできなくなる）

2023-04-25 01:40 UTC, acid-chicken commented on packages/backend/src/core/NoteCreateService.ts
>  		if (data.visibility === 'public' && data.channel == null) {
スコープ内に入れてください

2023-04-25 01:40 UTC, acid-chicken commented on packages/backend/src/core/NoteCreateService.ts
> +				data.visibility = 'home';
ここの順番の意図を教えてもらえますか？

2023-04-25 01:40 UTC, acid-chicken commented on packages/backend/src/core/NoteCreateService.ts
> +			if (matchRegex != null && matchRegex.length > 2) {
ここだけフラグを想定している、というかここ自体いらない

2023-04-25 01:40 UTC, acid-chicken commented on packages/backend/src/core/NoteCreateService.ts
> +				const regex = new RegExp(matchRegex[1]);
```suggestion
				const regex = new RE2(sensitiveWord.slice(1, -1));
```

2023-04-25 01:40 UTC, acid-chicken commented on packages/backend/src/core/NoteCreateService.ts
> +	private isSensiteive(sensitiveWord: string, word:string):boolean {
```suggestion
	@bindThis
	private isSensiteive(sensitiveWord: string, word: string): boolean {
```

2023-04-25 01:54 UTC, nenohi commented on packages/backend/src/core/NoteCreateService.ts
> +				data.visibility = 'home';
特に考えてなかったです、元々あったのに後々追加したので、順番的にはテキスト、注釈、ロールの順でチェックのほうがいいと思うので修正します

2023-04-25 01:55 UTC, acid-chicken commented on packages/backend/src/core/NoteCreateService.ts
> +					const matchRegex = /\/(.*)\/(.*)/g.exec(w);
デフォルト iu でいい説

2023-04-25 02:02 UTC, nenohi commented on packages/backend/src/core/NoteCreateService.ts
> +						return regex.test(data.text!);
あーーーそれは想定してなかったです

2023-04-25 02:22 UTC, nenohi commented on packages/backend/src/core/NoteCreateService.ts
> +					const matchRegex = /\/(.*)\/(.*)/g.exec(w);
iuだと別な単語のときに小文字抜きたい(カスタム絵文字)とかがありそうだからこのままでいいかも？

2023-04-25 02:25 UTC, u1-liquid commented on packages/backend/src/core/NoteCreateService.ts
> +					const matchRegex = /\/(.*)\/(.*)/g.exec(w);
フラグに関してはインライン設定`(?iu)`でも使えるはずなのでデフォルトはgだけでいいかも

2023-04-26 04:17 UTC, acid-chicken commented
#10715 で調査した結果 RE2 であってもリストが大きいとめちゃくちゃ遅くなることがわかったので正規表現やりたくなさゲージが上昇した

2023-04-26 05:46 UTC, acid-chicken commented
というかよく考えたら misc/check-word-mute と共通化してよくね

2023-04-26 05:53 UTC, nenohi commented
たしかに

2023-04-27 04:12 UTC, nenohi commented
これ型が違うからマイグレーションが必要かも？
ワードミュート→jsonb
センシティブワード→varchar

2023-04-27 04:13 UTC, tamaina commented
jsonb <=> varcharのマイグレーション、不可能

2023-04-27 04:15 UTC, syuilo commented
JSの力を使えばそんなに難しくはない

2023-04-27 04:18 UTC, nenohi commented
```
const sensitive = sensitivewords.foreach(x=>x.split(' '))
```
みたいな感じで定義するってこと・・・？

2023-04-27 04:41 UTC, nenohi commented
> というかよく考えたら misc/check-word-mute と共通化してよくね

センシティブワードの場合、CWにセンシティブのものが入っておらず
textにセンシティブワードが入っていた場合はスルーにするべきだと思うので
共通化と言うよりは抜き出しのほうがいい感じしそう

2023-04-27 06:29 UTC, nenohi commented
正規表現反応してないかも

2023-04-28 06:46 UTC, nenohi commented
動いてるかも？

2023-04-28 06:47 UTC, tamaina commented
テスト書こうぜ

2023-04-28 07:51 UTC, nenohi commented
pnpm run test
でやるとfrontendのhome.test.tsでコケてそう

2023-04-28 12:32 UTC, nenohi commented
> misc/check-word-mute と共通化

文言の変更もします。

2023-04-28 12:56 UTC, nenohi commented
sita

2023-05-02 01:28 UTC, syuilo commented on packages/backend/src/core/NoteCreateService.ts
> +	private isSensiteive(text: string, sensitiveWord: string[]): boolean {
```suggestion
	private isSensitive(text: string, sensitiveWord: string[]): boolean {
```

2023-05-02 01:29 UTC, syuilo commented on packages/backend/src/core/NoteCreateService.ts
> +import { fill } from '@tensorflow/tfjs-core';
これ使ってる？

2023-05-03 16:47 UTC, nenohi commented on packages/backend/src/core/NoteCreateService.ts
> +import { fill } from '@tensorflow/tfjs-core';
使ってないかもなので消します

2023-05-03 16:48 UTC, nenohi commented on packages/backend/src/core/NoteCreateService.ts
> +	private isSensiteive(text: string, sensitiveWord: string[]): boolean {
これに追従して使用部分も変更しました

2023-05-04 15:08 UTC, nenohi commented
なんかマージミスってそう

2023-05-04 19:33 UTC, nenohi commented
うまくいかないのでリベースしてforcePushします(？)

2023-05-06 04:01 UTC, acid-chicken commented
> > というかよく考えたら misc/check-word-mute と共通化してよくね
> 
> センシティブワードの場合、CWにセンシティブのものが入っておらず
> 
> textにセンシティブワードが入っていた場合はスルーにするべきだと思うので
> 
> 共通化と言うよりは抜き出しのほうがいい感じしそう

について

> センシティブワードの場合、CWにセンシティブのものが入っておらず
> 
> textにセンシティブワードが入っていた場合はスルーにするべきだと思うので

が理由になっているのがよく分からない

2023-05-06 13:53 UTC, nenohi commented
>> というかよく考えたら misc/check-word-mute と共通化してよくね
>
> センシティブワードの場合、CWにセンシティブのものが入っておらず
> textにセンシティブワードが入っていた場合はスルーにするべきだと思うので
> 共通化と言うよりは抜き出しのほうがいい感じしそう

>  センシティブワードの場合、CWにセンシティブのものが入っておらず
> textにセンシティブワードが入っていた場合はスルーにするべきだと思うので

共通化した場合、センシティブワードに含まれているものでCWにしているものでも
強制的にホームになってしまって理不尽を感じるのでは？ということです

2023-05-06 13:54 UTC, nenohi commented
センシティブワードに含まれていてもCWを使用して注意を促すような場合はOKにしたいというお気持ち

2023-05-06 13:56 UTC, acid-chicken commented
string を引数に取っているに過ぎない（note を表すオブジェクトを取っていない）ので呼び出し元で如何様にもできるのでは？

2023-05-06 13:59 UTC, acid-chicken commented
仮にそうなっていなかったとしてもそうなるようにリファクタすれば良い

2023-05-06 16:12 UTC, nenohi commented
note取るか

2023-05-09 01:52 UTC, nenohi commented
noteからにした

2023-05-10 09:02 UTC, merged

2023-05-10 09:02 UTC, syuilo commented
👍🏻

2023-05-10 09:10 UTC, acid-chicken commented
引数が変わっただけで共通化はされてなくないか

https://github.com/misskey-dev/misskey/blob/11ea1a28110fb735462dbe1dbceb1ca58e206f32/packages/backend/src/core/NoteCreateService.ts#L676-L699
https://github.com/misskey-dev/misskey/blob/11ea1a28110fb735462dbe1dbceb1ca58e206f32/packages/backend/src/misc/check-word-mute.ts#L18-L65

このロジックが別々に存在しているのが嫌

2023-05-11 01:59 UTC, nenohi commented
共通化するにも型が別々なので難しいのでは・・・？
> ワードミュート→jsonb
> センシティブワード→varchar

2023-05-11 03:38 UTC, acid-chicken commented
なぜ DB の型が出てくるのか分からないが

> JSの力を使えばそんなに難しくはない

2023-05-11 05:10 UTC, nenohi commented
こういう感じ・・・？
https://github.com/nenohi/misskey/tree/fix-regsensitive

2023-05-11 05:23 UTC, acid-chicken commented
> こういう感じ・・・？ https://github.com/nenohi/misskey/tree/fix-regsensitive

概ねそうだけど正規表現の判定を最初にやる必要がある→正規表現ならそのまま、違うなら配列に包む

2023-05-11 05:28 UTC, acid-chicken commented
ただこれはミュート側の方を変更する余地大有りかも

2023-05-11 05:36 UTC, nenohi commented
ミュート側は`userId: Note['userId'];`が必須でセンシティブワード側にはないからという認識でいい？

2023-05-11 06:11 UTC, acid-chicken commented
> ミュート側は`userId: Note['userId'];`が必須でセンシティブワード側にはないからという認識でいい？

いや単純に `(string | string)[]` という引数がインターフェースとして意味がわからないため