[fix] .wav .flac ファイルを再生可能にする
misskey-dev/misskey pull request #10686
Opened 2023-04-21 22:54 UTC by yuriha-chan

## What
.wav ファイルと .flac ファイルを再生可能にするために、file-typeにより判定されたMIME Type(audio/vnd.wave, audio/x-flac)をHTML5 Audio/Video要素に認識されるもの(audio/wav, audio/flac)に書き換える。

https://github.com/misskey-dev/misskey/issues/10685

## Why
vue-plyrの使っているHTML5 audio タグは適切なMIME Typeが設定されていないと再生できない。
アップロード時に適切なMIMEタイプを設定することで再生されるようになる。

## Additional info (optional)
すでにアップロードされた .wavファイルや .flacファイルは再生可能にはならない。

## Checklist
- [ ✔ ] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [ ✔ ] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2023-04-22 05:32 UTC, tamaina requested changes

2023-04-22 05:32 UTC, tamaina commented on packages/backend/src/core/FileInfoService.ts
> +			let mime:string = type.mime;
```suggestion
			let mime: string = type.mime;
```

2023-04-22 05:48 UTC, acid-chicken commented on packages/backend/src/core/FileInfoService.ts
> +			let mime:string = type.mime;
というか推論されるから指定自体いらんくね

2023-04-23 16:47 UTC, yuriha-chan commented on packages/backend/src/core/FileInfoService.ts
> +			let mime:string = type.mime;
これを省くとなぜか typecheck で MimeType という謎の型に推論される
![image](https://user-images.githubusercontent.com/121590760/233853025-f517fb02-045e-4a18-9487-8bbc0729bb6c.png)

2023-04-25 16:59 UTC, tamaina commented
テストを追加した

2023-04-25 17:17 UTC, merged

2023-04-25 17:18 UTC, tamaina commented
🙏🙏🙏

2023-04-26 05:11 UTC, syuilo commented
🙏