Perf: Stop retrying to acquire lock for FetchInstanceMetadata
misskey-dev/misskey pull request #11128
Opened 2023-07-06 00:27 UTC by yuriha-chan

## What
Fixes #11000
インスタンスの情報のDB上の最終更新時刻を確認し、古かったら更新する操作がredis-lockにより排他制御されていたが、ロックを取得できなかった場合にリトライするのをやめ、何もしないようにした。

## Why
FetchInstanceMetadata は Deliver Jobから呼ばれるため高速大量に呼ばれるため、これを改めることでパフォーマンスが顕著に改善する。
このロックはインスタンス情報の更新操作が一回だけ行われることを目的としているため、ロックが取得できない場合、何もしないことに問題はない。

## Additional info (optional)
以下の動作を確認しました。
- Deliver完了時にInstance Metadataが正しく更新されることを確認した。
- 大量のDeliverを高速に行ったときに、パフォーマンスが改善することを確認した。

redis-lockにリトライを設定するオプションがなかったので、Redis上にロックとして使うキーを設定し、これをアトミックに参照・書き換える実装とした。

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [x] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2023-07-06 00:46 UTC, syuilo commented
テスト欲しくなってきたわね

2023-07-06 01:16 UTC, yuriha-chan commented
連合のテストやパフォーマンスのテストが結構やっかいなのですよね。
いま私が手動＆目視でやっているテストは、複数のサーバーを立ち上げてフォローさせ、APIで大量に投稿を投げるというテストです。
（production環境でもうまくいくかどうかを確かめるため、ほぼ本番環境とほぼ同様のサーバーをLAN内でオレオレ証明書で動かしています。`NODE_OPTIONS=–use-openssl-ca` と (/etc/hostsを使う場合）`cacheablelookup`の設定変更が必要。）

2023-07-06 01:17 UTC, syuilo commented
パフォーマンスのテストはそこまで重要じゃないと思っていて、このPRでいえば「ロックを取得できなかった場合にリトライするのをやめ、何もしないようになった」ことを担保するテストがあると良いかなと思った

2023-07-06 01:22 UTC, yuriha-chan commented
redisClientのモックを作ればそういうこともやりやすいかも。

2023-07-07 06:41 UTC, tamaina commented
@yuriha-chan 失礼ですが、エディタは何を使われていますか？

2023-07-07 06:50 UTC, tamaina commented on packages/backend/src/core/FetchInstanceMetadataService.ts
> +				const _instance = await this.instancesRepository.findOneBy({ host: instance.host });
ここが`federatedInstanceService.fetch()`でないのはなんでなんだ？

（そうしてもいい気がする）

@syuilo

2023-07-07 06:55 UTC, syuilo commented on packages/backend/src/core/FetchInstanceMetadataService.ts
> +				const _instance = await this.instancesRepository.findOneBy({ host: instance.host });
良さそう

2023-07-07 07:10 UTC, yuriha-chan commented
vimだけど設定に無頓着なせいで劣悪な環境で書いていたりしています

2023-07-07 07:10 UTC, tamaina commented
VS Codeを使ってくださいね。

2023-07-07 07:11 UTC, yuriha-chan commented
ぐぬぬ…

2023-07-07 07:50 UTC, tamaina approved these changes

2023-07-07 13:10 UTC, tamaina commented
（なんかもう全然ダメダメで笑うしかなくなった）

2023-07-07 13:18 UTC, tamaina requested changes

2023-07-07 13:18 UTC, tamaina commented on CHANGELOG.md
> +- ロック機構の見直しにより、連合の配送ジョブのパフォーマンスを向上しました
```suggestion
- 連合の配送ジョブのパフォーマンスを向上（ロック機構の見直し、Redisキャッシュの活用）
```

2023-07-07 13:18 UTC, tamaina approved these changes

2023-07-07 13:28 UTC, tamaina approved these changes

2023-07-07 14:28 UTC, merged

2023-07-07 14:28 UTC, tamaina commented
👍 👍👍👍