Feat graceful shutdown 終了時に穏便に死ぬようにする
misskey-dev/misskey pull request #11734
Opened 2023-08-17 14:47 UTC by fruitriin

## What

https://github.com/misskey-dev/misskey/issues/10995
Misskeyのバックエンドプロセスがちゃんと死ぬようにする

## Why

## Additional info (optional)
https://github.com/hemerajs/fastify-graceful-shutdown
こいつを入れる

## Checklist
- [ ] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [ ] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2023-08-19 10:46 UTC, syuilo commented
ありがとうございます 🙏🏻 

- チェックリストにある項目をご確認ください
- クォートを他の個所と統一してください
- 不必要なdiffが含まれています

2023-08-21 03:11 UTC, acid-chicken requested changes

2023-08-21 03:11 UTC, acid-chicken commented on packages/backend/package.json
> +		"fastify-graceful-shutdown": "^3.5.1",
devDependencies になっています

2023-08-21 11:42 UTC, EbiseLutica commented on packages/backend/src/server/ServerService.ts
> +import fasitfyGracefulShutdown from "fastify-graceful-shutdown"
細かいですが、誤字の修正をお願いします～！
 `fasitfy` → `fastify`

2023-09-18 04:37 UTC, syuilo commented
`Error: SIGINT handler was already registered use fastify.gracefulShutdown`が出る

2023-10-09 11:49 UTC, closed without merging