fix: 表示済みのカラムから別のチャンネルを選択した時、タイムラインの内容が追従して変更されない問題に対処
misskey-dev/misskey pull request #12237
Opened 2023-11-04 03:29 UTC by samunohito

## What

#12236 に対する対処です。
表示対象のチャンネルを切り替えた際に、切り替えた先のチャンネルのタイムラインを表示できるように修正しました。

channel-column.vueなどでチャンネルIDが変更された通知がMkTimeline.vueまで渡っておらず、更にMkTimeline.vueの中で作成しているMkPagination.vue用のパラメータ変更通知も渡っていないようでした。
また、チャンネルに限らずアンテナ、リスト、ユーザロールタイムラインも同様の現象が起こっていましたが、この対応で改善しています（HTL、LTL、STL、GTLは問題なかった）

## Why

カラムからチャンネルなどを変更した時、リロードしなければ表示が更新されないのは不自然なため

## Additional info (optional)

チャンネル、アンテナ、リスト、ユーザロールタイムラインを切り替えた際、即座に反映されることを確認

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment ※デッキ周りの表示テストはなさそう？
- [ ] (If needed) Add story of storybook
- [x] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2023-11-04 23:27 UTC, syuilo requested changes

2023-11-04 23:27 UTC, syuilo commented on packages/frontend/src/components/MkPagination.vue
> -import MkButton from '@/components/MkButton.vue';
MkButtonは使われてますね

2023-11-04 23:32 UTC, syuilo commented on packages/frontend/src/components/MkTimeline.vue
> +onBeforeUpdate(refreshEndpointAndChannel);
特定のpropをwatchする方がよさそう

2023-11-05 02:16 UTC, samunohito commented on packages/frontend/src/components/MkPagination.vue
> -import MkButton from '@/components/MkButton.vue';
復活させました。MkLoading、MkErrorとかもimportが無かったのでついでに増やしています
6d5058c

2023-11-05 02:22 UTC, samunohito commented on packages/frontend/src/components/MkTimeline.vue
> +onBeforeUpdate(refreshEndpointAndChannel);
全体を監視するのを辞めて、リスト、ID、チャンネル、ロールタイムラインの各IDのみを監視するようにしました
（withRenotesとかはdevelopの状態でも動いてるっぽかったので）

6d5058c

2023-11-06 22:47 UTC, samunohito commented
（CHANGELOG.mdに書いた変更内容の差分がリリース済みバージョンの所にあるので、次バージョンの欄ができたらそちらにうつします）

2023-11-10 10:18 UTC, samunohito commented
@syuilo 
CHNANGELOG.mdの記述箇所変更や最新追従もろもろメンテしてますので、再びご確認頂けますと幸いでございます:pray:

2023-11-11 07:08 UTC, syuilo commented on packages/frontend/src/components/MkPagination.vue
> -import MkButton from '@/components/MkButton.vue';
MkLoading、MkErrorはグローバルコンポーネントなのでimportの必要はないですね👀

2023-11-15 02:24 UTC, merged

2023-11-15 02:25 UTC, syuilo commented
🙏🏻 🙏🏻 🙏🏻