Feat: 予約投稿
misskey-dev/misskey pull request #12265
Opened 2023-11-06 09:17 UTC by mattyatea

## What

予約投稿が追加されます。
作業中です。

## Why

予約投稿がないと不便だという意見もみられるため？
## Additional info (optional)

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2023-11-06 09:19 UTC, mattyatea commented
redisに保存するようになってるからredis飛んだときとかがあれかもしれない
けどdbに保存するとなると毎分dbにアクセスしなくちゃいけないから...って思ってます

2023-11-06 10:34 UTC, kakkokari-gtyih commented
- 予約投稿専用IDを発番する
- そのIDと投稿時刻をRedisに突っ込む

で解決できそう（ついでに予約一覧の表示もやりやすくなるかも？）

2023-11-08 22:26 UTC, kakkokari-gtyih commented on packages/backend/src/queue/processors/ScheduleNotePostProcessorService.ts
> +		this.logger = this.queueLoggerService.logger.createSubLogger('ended-poll-notification');
変更忘れ？

2023-11-09 07:11 UTC, mattyatea commented on packages/backend/src/queue/processors/ScheduleNotePostProcessorService.ts
> +		this.logger = this.queueLoggerService.logger.createSubLogger('ended-poll-notification');
変更忘れです 🥴

2023-11-09 08:37 UTC, kakkokari-gtyih commented
UI周りちょっと見てみてもいいすか？

2023-11-09 09:31 UTC, kakkokari-gtyih commented
やろうとしてること

- 予約投稿関連のエンドポイントを全部`/api/notes/schedule/`配下に置き直す
- 予約投稿単体でダイアログ出せるように
- 投稿編集時はPostFormの表記を変更するように
- その他フロントエンドの細かい調整

2023-11-09 09:36 UTC, mattyatea commented
そこ周り少し変更加えたので一回pushします

2023-11-09 10:03 UTC, kakkokari-gtyih commented
> 予約投稿関連のエンドポイントを全部/api/notes/schedule/配下に置き直す

（やったけど変なところにpushしてしまったので少々お待ちください）

2023-11-09 12:24 UTC, kakkokari-gtyih commented
- 予約投稿一覧にMkPaginationをつける（一応）
  - （API側でPaginationQueryを使う）
- 予約投稿の時刻設定をUNIXタイムスタンプではなくISO8601で指定できるようにする

くらいかなと

2023-11-09 12:27 UTC, syuilo requested changes, later dismissed
NoteSchedule --> ScheduledNote
(一括置換)

2023-11-09 12:28 UTC, syuilo commented
> NoteSchedule --> ScheduledNote (一括置換)

あーノートというよりスケジュール自体だからいいのか？

2023-11-09 12:32 UTC, syuilo commented on packages/backend/src/server/api/endpoints/notes/schedule/create.ts
通常のノート作成と被ってる処理が多そう

2023-11-09 12:35 UTC, kakkokari-gtyih commented
> NoteSchedule --> ScheduledNote (一括置換)

完了

2023-11-09 12:35 UTC, kakkokari-gtyih commented on packages/backend/src/server/api/endpoints/notes/schedule/create.ts
それはそう（cc: @mattyatea ）

2023-11-09 12:38 UTC, kakkokari-gtyih commented
@syuilo この仕様で行くとDBから直読み込みで現状読み込みが遅くなることってありそうですかね
（ドライブのファイルがついたやつ表示機能の二の舞いは踏みたくない）

2023-11-09 12:41 UTC, syuilo commented
当該箇所(DBから読み込んでる箇所)って例えばどこのことかしら？(量が多くてまだ全体を把握できてない)

2023-11-09 12:44 UTC, syuilo commented on packages/backend/src/server/api/endpoints/notes/schedule/create.ts
共通化しないと通常投稿と予約投稿で挙動が異なる未来が視える

2023-11-09 12:48 UTC, kakkokari-gtyih commented
> 当該箇所(DBから読み込んでる箇所)って例えばどこのことかしら？(量が多くてまだ全体を把握できてない)

- packages/backend/src/server/api/endpoints/notes/schedule/list.ts 
- packages/backend/src/queue/processors/ScheduleNotePostProcessorService.ts

の、予約投稿IDもしくはユーザーIDでノートを絞り込んで抽出する部分です

2023-11-09 12:52 UTC, kakkokari-gtyih commented on misskey-assets
なんでこれがアップデートされてるのかしら

2023-11-09 13:04 UTC, syuilo commented
> > 当該箇所(DBから読み込んでる箇所)って例えばどこのことかしら？(量が多くてまだ全体を把握できてない)
> 
> * packages/backend/src/server/api/endpoints/notes/schedule/list.ts
> * packages/backend/src/queue/processors/ScheduleNotePostProcessorService.ts
> 
> の、予約投稿IDもしくはユーザーIDで予約投稿用ノートを絞り込んで抽出する部分です

IDに対するwhereだけなら全く問題ない

2023-11-09 13:07 UTC, kakkokari-gtyih commented
そうなんですね

2023-11-09 13:32 UTC, kakkokari-gtyih commented
あとは `expiresAt` → `publishesAt` とかかな

2023-11-09 13:38 UTC, kakkokari-gtyih commented on packages/backend/src/server/api/endpoints/notes/schedule/create.ts
`notes/create` にエンドポイントを一本化してみます

2023-11-09 13:54 UTC, kakkokari-gtyih commented on packages/backend/src/server/api/endpoints/notes/schedule/delete.ts
> +			await this.scheduledNotesRepository.delete({ id: ps.noteId });
ここで当該のJobも削除しておかないと面倒なことになりそう

2023-11-09 13:58 UTC, kakkokari-gtyih commented on packages/backend/src/server/api/endpoints/notes/schedule/delete.ts
> +			await this.scheduledNotesRepository.delete({ id: ps.noteId });
jobIdとscheduledNoteIdを同一のものにして削除できるようにした

2023-11-09 14:33 UTC, kakkokari-gtyih commented on packages/backend/src/server/api/endpoints/notes/schedule/list.ts
>  						id: item.id,
工数は増えるもののやはりここはしっかり区別させたい

2023-11-09 14:39 UTC, kakkokari-gtyih commented on packages/backend/src/server/api/endpoints/notes/schedule/create.ts
した

2023-11-09 15:28 UTC, kakkokari-gtyih commented
## やったこと

- UIの調整をした
  - 投稿フォームをすっきりさせた（一部メニューを省略）
  - 予約投稿送信後にtoastを表示させるようにした
  - 説明を増やした
  - 予約投稿がないときに「ありません」が出るようにした
  - ナビゲーションバーに予約投稿一覧を出せるようにした
- 予約投稿関連のエンドポイントを全部`notes/schedule/`配下に置き直した
- 投稿作成のエンドポイントを`notes/create`に一本化（バリデーションを共通化するため）
- 予約投稿のJob IDを予約投稿IDとそろえた
  - 予約投稿を削除する際に、予約投稿のQueueも削除されるように修正
- 大半のエンティティ名を変更

## まだやってないけどやったほうがいいこと

- [ ] `expiresAt` を `publishAt` などに変更する
- [ ] 予約投稿APIはページネーションクエリで呼べるようにする
  - [ ] 予約投稿一覧にMkPaginationをつける
- [ ] 予約投稿の時刻設定をISO8601で指定できるようにする
- [ ] ノートのIDと予約投稿IDをちゃんと区別する
- [ ] 予約投稿ノートを編集できるようにする

2023-11-10 10:35 UTC, kakkokari-gtyih commented
@mattyatea ちょっと今忙しいので一旦お戻しします（そちらで進められそうなら進めておいてください）🙏

2023-11-11 09:56 UTC, kakkokari-gtyih commented
@syuilo 近い将来にノート編集機能を実装する予定があるなら予約投稿の編集をいまのうちから`notes/update`でできるようにしておいてもいいかも（実装予定がないなら`notes/schedule/update`にしておく）

2023-11-11 10:08 UTC, kakkokari-gtyih commented
予約投稿の編集、実装しんどいわりに今後使い回されることが多そうなので、一旦「削除して編集」にしておいてもいいかも

2023-11-14 08:30 UTC, mattyatea commented on misskey-assets
不明

2023-11-20 10:28 UTC, kakkokari-gtyih commented
> 予約投稿の編集、実装しんどいわりに今後使い回されることが多そうなので、一旦「削除して編集」にしておいてもいいかも

こうするか

2023-11-24 07:38 UTC, kakkokari-gtyih commented
Codecovに怒られてるの気になる

2023-11-24 11:42 UTC, kakkokari-gtyih commented
（ただどうやって直せばいいかはわからん）

2023-11-25 20:20 UTC, mattyatea commented
削除して編集実装した

2023-11-27 12:13 UTC, kakkokari-gtyih commented
https://github.com/misskey-dev/misskey/pull/12265/commits/28ee4d47c0b240db6eb30e14291e44862b1f7484 のUI直したらひとまずリリースしてもよさそう

2023-11-29 06:11 UTC, kakkokari-gtyih commented
@mattyatea 予約投稿に設定していた時間帯にサーバーが落ちていた場合、復旧時どういう挙動をするのか（次回サーバー起動時にまとめて投稿されるのか、それともエラーとして投稿せずにキューから消えるのか）は確認しておいたほうがいいかも

2023-12-02 01:44 UTC, kakkokari-gtyih commented
https://github.com/misskey-dev/misskey/pull/12265/commits/f1b608ff05118abe33eaa2104233ea49506a71ce のコンフリクト解消時にシンタックスエラー発生した（メモ）

2023-12-06 12:55 UTC, kakkokari-gtyih commented
## TODO（最新版）

- [ ] Job実行に失敗した際の挙動を確認する（再起動時に実行されるのはまずいので、その場合はJob実行をあきらめるようにすべき）
- [ ] 予約投稿であることを示すフラグ `isScheduled` をノートにつける＋ノートの時間表示の横に 🕑 マークを表示する
- [ ] 予約投稿に失敗した場合に通知を発行する
- [ ] Codecovってどうなの？ (cc: @syuilo )

2023-12-06 13:12 UTC, kakkokari-gtyih commented
> 現在ジョブ実行に失敗したら そもそも実行されない みたいな挙動になってる

一応、JobProcessorのほうに、指定時刻から1分以上過ぎてたらreturnとか入れておいても良いかも

2023-12-06 16:05 UTC, kakkokari-gtyih commented
> 現在ジョブ実行に失敗したら そもそも実行されない みたいな挙動になってる

JobのDelayがダウンタイム分だけ延長された可能性ない？

2024-01-02 09:44 UTC, kakkokari-gtyih commented on packages/backend/src/queue/processors/ScheduleNotePostProcessorService.ts
> +					await this.scheduledNotesRepository.remove(data);
これ消さない方がいい気が（失敗したという情報をscheduledNoteに載せられるようにして、再投稿とかでデータを流用できるようにしたほうが良いかも）

2024-01-02 11:00 UTC, mattyatea commented on packages/backend/src/queue/processors/ScheduleNotePostProcessorService.ts
> +					await this.scheduledNotesRepository.remove(data);
消さないようにしてisFailedがtrueになるようにしました

2024-01-02 12:45 UTC, kakkokari-gtyih commented
`pnpm build-misskey-js-with-types`

2024-01-02 12:47 UTC, mattyatea commented
ありがとうございます🙏

2024-02-08 04:00 UTC, kakkokari-gtyih commented
> Github Workflowのマージに失敗してる（バージョンが戻されてる）ので元に戻す

いけた（ので動作確認だけしたらreadyにできそう）

2024-02-08 04:28 UTC, kakkokari-gtyih commented
submoduleのdiffだけ取っ払いたい

2024-02-08 05:26 UTC, syuilo commented on packages/backend/src/models/ScheduledNote.ts
> +@Entity('note_schedule')
クラス名と一致してないわね

2024-06-21 15:12 UTC, closed without merging