dev: fix misskey-tga
misskey-dev/misskey pull request #13312
Opened 2024-02-15 07:09 UTC by Srgr0

## What
PRコメントでの実行時、PR元のリポジトリを使用するように修正

## Why
PR元のブランチはPR元のリポジトリにあるため。

## Additional info (optional)

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2024-02-15 15:38 UTC, anatawa12 commented
tga的に無理だったらこの方針でいいと思うんだけど、`refs/pull/<number>/head` を使ったほうがシンプルな気がしました。

2024-03-02 02:33 UTC, Srgr0 commented
変更しました。

2024-03-05 11:56 UTC, anatawa12 requested changes
また、確認したところbash-installのほうのここの行がref指定だとうまく動かなそうでしたのでこちら側も修正が必要だと思います。

https://github.com/joinmisskey/bash-install/blob/3c999ddbc7f44685c247db0d60d7b73ccfcbb6d6/misskey-install.sh#L924

個人的な考えですが、ref対応のためには`git init`, `git remote add origin <url>`, `git fetch origin <ref>`, `git checkout <branch_name> FETCH_HEAD`するのがいいと思っています

2024-03-05 11:56 UTC, anatawa12 commented on .github/workflows/deploy-test-environment.yml
> +      repository: ${{ needs.get-pr-ref.outputs.pr-repo }}
多分ここは`${{ github.repository }}` のままの方が正しいと思います

2024-03-11 01:37 UTC, samunohito commented
@Srgr0 
ご状況はいかがでしょうか…？

2024-04-02 12:57 UTC, anatawa12 commented on .github/workflows/deploy-test-environment.yml
> +      repository: ${{ needs.get-pr-ref.outputs.pr-repo }}
```suggestion
      repository: ${{ github.repository }}
```

2024-04-02 13:12 UTC, anatawa12 approved these changes
多分この状態なら問題ないと思います

2024-04-08 13:41 UTC, merged

2024-04-08 13:41 UTC, syuilo commented
🙏🙏🙏