enhance: 通知がミュートを考慮するようにする
misskey-dev/misskey pull request #13412
Opened 2024-02-19 15:43 UTC by tai-cha

## What

ミュートしたユーザーからの通知が出ないようにした

## Why

resolve #13411 

## Additional info (optional)

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [ ] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2024-02-19 15:45 UTC, tamaina commented
凍結も…

2024-02-19 15:47 UTC, tai-cha commented
別トピックだから同時にやらないほうがいいかなと思ったんですが凍結も一緒にしちゃっていいか

2024-02-19 15:51 UTC, tamaina commented
マージするのが大変なんじゃないかしら

2024-02-19 15:52 UTC, tamaina commented
（コンフリクトしなくても個人的には一緒でいいと思っている（PRの粒度については諸説ある

2024-02-19 15:53 UTC, tai-cha commented
テスト書いたらdraft外したい

2024-02-19 15:54 UTC, tamaina commented
（はっや（ここまで簡単だと思ってなかった

2024-02-19 15:59 UTC, tai-cha commented
そりゃUserの実体取らざるを得ないから凍結も取得簡単

2024-02-19 16:20 UTC, tamaina commented
notifierIdを持たないタイプの通知がnullになって全部消されてる気がする

2024-02-19 16:21 UTC, tai-cha commented
あ！（なおします）

2024-02-19 16:22 UTC, tamaina commented
あとこのロジックをNotificationEntityService.pack系に書かなかったのはなぜかしら

2024-02-19 16:24 UTC, tai-cha commented
> あとこのロジックをNotificationEntityService.pack系に書かなかったのはなぜかしら

- とりあえず書いたから

そのほうが良さそうなのでテスト書いた後にやるか

2024-02-19 16:25 UTC, tai-cha commented
ついでに言うとGroupedとそうじゃないもので二重になってる箇所があるのでリファクタしたい

2024-02-19 16:34 UTC, tai-cha commented on packages/backend/src/server/api/endpoints/i/notifications-grouped.ts
> +import { not } from 'ajv/dist/compile/codegen/index.js';
なにこれ
```suggestion
```

2024-02-19 16:37 UTC, tamaina commented on packages/backend/src/server/api/endpoints/i/notifications-grouped.ts
> +import { not } from 'ajv/dist/compile/codegen/index.js';
noteとか書こうとしてnotの時点でenterしてVS Code(かなんかのIDE)のサジェスチョンが突っ込まれたと予想

2024-02-19 16:37 UTC, tamaina commented
>  enhance: 通知がミュート・通知を考慮するようにする

おちつけ

2024-02-19 16:38 UTC, tai-cha commented
凍結って打ったつもりしかなかった

2024-02-20 05:23 UTC, tai-cha commented
（Serviceが要求を返せない場合のベストプラクティスがわかっていない）

2024-02-20 05:35 UTC, tai-cha commented
通知の発行時の挙動さえ決めちゃえば多分完成

2024-02-20 05:39 UTC, tai-cha reviewed
nullでいいんかな？のやつ

2024-02-20 05:39 UTC, tai-cha commented on packages/backend/src/core/entities/NotificationEntityService.ts
> +
ここ

2024-02-20 05:39 UTC, tai-cha commented on packages/backend/src/core/entities/NotificationEntityService.ts
> +
ここ

2024-02-20 05:41 UTC, tai-cha commented
別に作成時ぐらいにしか使われないpackは今回はいじらない手もあるか？と思ったけど通知の作成イベントが飛んでしまうな

2024-02-20 05:43 UTC, tai-cha commented
（なんで今不完全なのにテスト全部通ってるんだ・・・）

2024-02-20 05:46 UTC, tai-cha commented
あー別にinternalであるから帰ってきてる結果がなくても今のところ問題がないんだ

2024-02-20 05:54 UTC, tai-cha commented
あーpackManyって結局pack呼ぶのか（勘違いしていた）

2024-02-20 06:16 UTC, tamaina commented
なんかねという感じはある

(凍結やミュートをチェックしたいときは外からはpackMany([MiNotification])みたいに呼ぶという運用にすればいいのかも

2024-02-20 06:17 UTC, tai-cha commented
packManyでやった方が問い合わせが少ないのでパフォーマンスは高いんだよな（オプション引数とってチェックする部分スキップさせればいいのか）

2024-02-20 06:24 UTC, tai-cha commented
多分めんどくさい運用考えなくてもこれで直感的に書けるでしょの気持ち（テスト通ればこれで一旦完成の気持ち）

2024-02-20 06:25 UTC, tai-cha commented
本当はミュートしたら通知リロードさせたいけどめんどくさい

2024-02-20 06:27 UTC, tai-cha commented on packages/backend/src/core/entities/NotificationEntityService.ts
> +		}))) as [T|null] ).filter((notification): notification is T => notification !== null);
```ts
		}))) as [T|null] ).filter((notification): notification is T => notification !== null);
```
`[T|null]`を明示しないと`Awaited<T|null>`としか認識してくれなかったので困ったやつ

2024-02-20 06:49 UTC, tai-cha commented
もしかして：
https://github.com/misskey-dev/misskey/pull/13284

とまるっきり競合するかも

2024-02-20 06:59 UTC, tamaina commented
> 本当はミュートしたら通知リロードさせたいけどめんどくさい

これは別prにしたほうがよさそう

2024-02-20 06:59 UTC, tai-cha commented
とりあえずこれマージされそうだったら別Issueにしよう

2024-02-20 18:08 UTC, tai-cha commented
#13284 をここにマージした

2024-02-20 19:22 UTC, tai-cha commented
Note: GroupedNotificationはNotificationの拡張なのでそれに対する例外だけ書けば基本的に共通の処理になり複雑な個別の処理は増えにくいと思われる

2024-02-21 11:23 UTC, syuilo commented
pack時に弾く感じかしら

2024-02-21 11:25 UTC, tai-cha commented
pack時に弾くようにした（さいしょはapiで弾いていたけどこっちのほうが良くないって@tamaina に言われてたしかにとなったため）

2024-02-21 11:27 UTC, tai-cha commented
packかpackManyどちらかで弾かれる（Manyの場合は複数一気にやる、パフォーマンス上の都合）

2024-02-21 11:28 UTC, syuilo commented
自分がミュートしたか、ユーザーが凍結された時にRedisから消した方がスッキリしそうなのとパフォーマンス的にも良さそうな気がした

2024-02-21 11:30 UTC, tai-cha commented
すでに来てるやつは消えないけど一理ある

2024-02-21 11:31 UTC, syuilo commented
すでに来てるやつは消えない というと？

2024-02-21 11:32 UTC, tamaina commented
> Redisから消した方が

ｗ読んでなさそう

2024-02-21 11:34 UTC, tai-cha commented
それだったらこの前まで書いてた個別削除のロジックを流用した別PRにしたほうがいいかも（このPRずっと見てた @tamaina さんはどっちがいいと思うか聞きたさはある）

2024-02-21 11:35 UTC, tai-cha commented
あーredisから個別で対象の通知消そうとすると消すときにたくさんnotificationsを読む必要があるからいうほどパフォーマンス良くないかも

2024-02-21 11:36 UTC, syuilo commented
ミュートや凍結が行われる数 < 通知が読まれる数
と思う

2024-02-21 11:39 UTC, tai-cha commented
スパムとかたくさん湧くと結構凍結発生するのとサーバーブロックの場合はたくさんミュートすることになるかも、流石に通知を読む数のが少ないけど

2024-02-21 11:41 UTC, tamaina commented
Redisから消すの、notifierIdをRedisで絞って消せるならいいけどそうじゃないならRedisの全部の通知をJSON.parseして処理することになりそう？

2024-02-21 11:41 UTC, tai-cha commented
> あーredisから個別で対象の通知消そうとすると消すときにたくさんnotificationsを読む必要があるからいうほどパフォーマンス良くないかも

これ、凍結の場合は全ユーザー分の探索が必要なのでやばい

2024-02-21 11:42 UTC, syuilo commented
データの持ち方を工夫すれば大丈夫そう

2024-02-21 11:43 UTC, tai-cha commented
どう工夫すればいいか今のところアイデアがない

2024-02-21 11:43 UTC, syuilo commented
考える

2024-02-21 11:43 UTC, tamaina commented
通知また全消しするのか…とりあえずいまはpackでサクッと実装したい気分

2024-02-21 11:44 UTC, syuilo commented
通知また全消しするのか というと？

2024-02-21 11:50 UTC, tai-cha commented
> Redisから消すの、notifierIdをRedisで絞って消せるならいいけどそうじゃないならRedisの全部の通知をJSON.parseして処理することになりそう？

実際にキーを増やすとか変えるじゃないと多分そうなってしまう

2024-02-21 11:52 UTC, tamaina commented
> 通知また全消しするのか というと？

データの持ち方を変えるとなるとそういうこともありそう

2024-02-21 11:53 UTC, syuilo commented
変え方によってはそういうこともあるけど新たにインデックスのようなデータを持たせることを考えている

2024-02-21 11:54 UTC, tai-cha commented
消さないでやろうとするとFTTの条件のやつみたいにキーを増やしてそれを一気に取得するとかになりそうだけどそれはそれで

2024-02-21 11:58 UTC, tamaina commented
古いデータ消せないなと思ったけどまあ別にいいか

2024-02-21 12:00 UTC, tai-cha commented
まあ古いデータは全削除してもらうのがいいのかも、でも持ち方の変え方次第では全削除の方にも影響するな

2024-02-21 12:03 UTC, tai-cha commented
今のやり方でも毎packManyごとに重い読み込みが発生しなければいい説があるのでそっちの線の考えるか

2024-02-21 17:24 UTC, tamaina requested changes, later dismissed

2024-02-21 17:24 UTC, tamaina commented on packages/backend/src/core/entities/NotificationEntityService.ts
> +		return this.#validateNotifier(notification, userIdsWhoMeMuting, userMutedInstances, notifiers);
```suggestion
		return (await this.#filterValidNotifier([notification], meId)).length === 1;
```

2024-02-21 18:12 UTC, tamaina commented
packManyでNoteReadService.readを行うことで`this.notesRepository.findBy({ id: In(noteIds) })`の回数を減らしてみた

2024-02-21 18:20 UTC, tamaina commented
NOTE_REQUIRED_NOTIFICATION_TYPESのチェックっているの?

2024-02-21 20:37 UTC, tai-cha commented
寝てたらめっちゃ変わってる、確認するか

2024-02-21 21:06 UTC, tai-cha reviewed
めっちゃ綺麗になっている上にパフォーマンス向上していそう

2024-02-23 10:10 UTC, tai-cha commented
> packに副作用があるのはちょっと宜しくないかも

というとpackで通知を弾くのではなくこのPRで最初に実装したようにAPIコールの方でpackの前や後に凍結やミュートを考慮したほうが良いという話？

2024-02-23 10:11 UTC, syuilo commented
pack内でノートの既読処理はしない方が良さそう

2024-02-23 10:17 UTC, tai-cha commented
あーなるほど
それ直したら他には問題なさそうですか？

2024-02-23 17:01 UTC, tai-cha commented
既読処理の部分元通りにした

2024-02-23 18:55 UTC, tai-cha commented
e2e落ちるけど
  ● Account Move › Local to Local › A locked account automatically accept the follow request if it had already accepted the old account.

だからこのPRの変更と関係なさそう

2024-02-28 07:55 UTC, syuilo commented on packages/backend/src/core/entities/NotificationEntityService.ts
> +	async #validateNotifier <T extends MiNotification | MiGroupedNotification> (
async要素ないかも

2024-02-28 08:06 UTC, syuilo commented on packages/backend/src/core/entities/NotificationEntityService.ts
> +			if (!reactions.length) {
```suggestion
			if (reactions.length === 0) {
```

2024-02-28 08:06 UTC, syuilo commented on packages/backend/src/core/entities/NotificationEntityService.ts
> +			if (!users.length) {
```suggestion
			if (users.length === 0) {
```

2024-02-28 08:09 UTC, syuilo commented on packages/backend/src/core/NotificationService.ts
> +		if (packed === null) return null;
```suggestion
		if (packed == null) return null;
```

2024-02-28 08:10 UTC, syuilo commented on packages/backend/src/core/entities/NotificationEntityService.ts
> +		}))) as [T|null] ).filter(isNotNull);
```suggestion
		}))) as [T | null] ).filter(isNotNull);
```

2024-02-28 08:10 UTC, syuilo commented on packages/backend/src/core/entities/NotificationEntityService.ts
> +		if (notifier === null) return false;
```suggestion
		if (notifier == null) return false;
```

2024-02-28 09:22 UTC, tai-cha commented on packages/backend/src/core/entities/NotificationEntityService.ts
> +		if (notifier === null) return false;
:+1::bow:

2024-02-28 09:24 UTC, tai-cha commented on packages/backend/src/core/entities/NotificationEntityService.ts
> +	async #validateNotifier <T extends MiNotification | MiGroupedNotification> (
最初はあったから名残かも（確認して必要に応じて消します）

2024-02-28 10:33 UTC, tai-cha commented on packages/backend/src/core/entities/NotificationEntityService.ts
> +	async #validateNotifier <T extends MiNotification | MiGroupedNotification> (
Fixed

2024-02-28 12:26 UTC, merged

2024-02-28 12:26 UTC, syuilo commented
🙏