fix(frontend): ノートの詳細ページのユーザーもしくはチャンネルを遡るとタイムラインの並び順番が逆になる問題を修正
misskey-dev/misskey pull request #13585
Opened 2024-03-17 10:24 UTC by kakkokari-gtyih

## What

Cherry-picked from https://github.com/MisskeyIO/misskey/pull/529
Ref'ed https://github.com/MisskeyIO/misskey/pull/536

## Why

Fix #12625 

## Additional info (optional)

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [ ] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [x] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2024-03-17 12:23 UTC, yulog commented
#12625 が解消されますか？

2024-03-18 11:18 UTC, u1-liquid commented
これTLの順番が逆になるのは直してるけどfetchMoreボタンが下にできてしまうためちょっと微妙になった
MkPaginationにreversedの他にdirectionを指定するオプションが必要

2024-03-18 12:33 UTC, u1-liquid commented
そもそも「表示を上下逆にする機能」と「もっと見るボタンを置く場所の指定」は分離しておいた方がいいかも
`pages/note`の場合「表示は通常通り最新が上」でいいけど「もっと見るボタンは上に置きたい」状態ですので

全く確認してないけどおそらくこの辺を最初に作った時は以前の投稿を上に出して次の投稿を下に出すようにしようとしてたから`pagenation`が`reverse`状態で合ってたと思うけどどっかのタイミングで表示の場所をTLと同じように直してreverseを触ってないということじゃないかなと思う

2024-03-18 12:38 UTC, u1-liquid commented
せっかく触るならprependじゃなくて`direction: 'up' | 'down' | 'both'`にしてタイムマシン機能復活させようぜ（脱線）

2024-03-25 11:57 UTC, syuilo commented
関係あるかわからないけどsinceIdを指定してusers/notesにリクエストしたときに並び順が逆になってるバグを見つけた

2024-03-25 11:59 UTC, syuilo requested changes
FTTが無効になってるときに、このPRを適用すると逆になる

2024-03-25 12:02 UTC, closed without merging

2024-03-25 12:02 UTC, syuilo commented
クライアントではなく、バックエンドのバグ

2024-03-25 12:03 UTC, syuilo commented
🙏🏻