配信停止したインスタンス一覧が見れなくなる問題を修正
misskey-dev/misskey pull request #13945
Opened 2024-06-03 09:37 UTC by GrapeApple0

## What

インスタンス一覧で配信停止でフィルターをかけると一覧が見れなくなる問題を修正しました
## Why

fix: #13930
## Additional info (optional)

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2024-06-04 07:59 UTC, tai-cha approved these changes
ありがとうございます:+1:

2024-06-06 11:13 UTC, tai-cha commented
ApproveしたけどCHANGELOGないですねそういえば

2024-06-06 11:13 UTC, tai-cha requested changes
CHANGELOG足していただけると助かります
（もし御多忙でしたら代わりに私がやるのでもよいのでその場合は仰っていただければ）

2024-06-06 12:57 UTC, tai-cha approved these changes

2024-06-07 05:46 UTC, merged

2024-06-07 05:46 UTC, syuilo commented
🙏🏻