fix(backend): Webhook Test一致性+リアクションhook実装
misskey-dev/misskey pull request #14863
Opened 2024-10-29 00:46 UTC by eternal-flame-AD

This fixes #14862 

## What

1. Webhook Payload Schema
2. Make test payload consistent with actual payload (type checked)
3. Implemented webhook for reactions (added TS assertion for missing implementations).
4. Unit Test Corrections

<details>
<summary>Sample</summary>

```json
{"server":"https://mi.yumechi.jp","hookId":"9zrajfd0cq2o01rz","userId":"9vaew1esmfme0001","eventId":"ddaacf8b-8dc9-4064-b1f4-9d0ed503a08b","createdAt":1730162473582,"type":"reaction","body":{"note":{"id":"9zw05xzs9qgo00pa","createdAt":"2024-10-28T03:07:33.592Z","userId":"9vaew1esmfme0001","user":{"id":"9vaew1esmfme0001","name":"Yumechi | ゆめち | :ferris: :haskell: Wheel Inventor","username":"yume","host":null,"avatarUrl":"https://mi.yumechi.jp/proxy/avatar.webp?url=https%3A%2F%2Fmi.yumechi.jp%2Ffiles%2Fa6c26c37-ce9d-4d4f-996b-867bce841930&avatar=1","avatarBlurhash":"eIGtyd-.kB^jt7Ip-o?FM|M|0MxZxZRkNI~TIqWX%Ks.t6s.odR*xZ","avatarDecorations":[],"isBot":false,"isCat":true,"emojis":{},"onlineStatus":"online","badgeRoles":[]},"text":"诶好心疼。。痛苦真的是这样的 在绝望的环境里痛苦是麻木的，但实际上不知不觉中shape一个人的思维方式，让ta对这些痛苦越来越敏感\n\n有了那么一点自由以后突然被提醒自己的痛苦 立马就会回到原来的无法解脱的心境中 :blobcat_fu_sorry3:","cw":"わた婚E04","visibility":"public","localOnly":false,"reactionAcceptance":"nonSensitiveOnly","renoteCount":0,"repliesCount":1,"reactionCount":3,"reactions":{"❤":3},"reactionEmojis":{},"reactionAndUserPairCache":["9y780ob15vwvjeju/❤","9vd7pctq0z3k3jq5/❤","9zvytmeo9qgo00ma/❤"],"fileIds":["9zw05ixl9qgo00p9"],"files":[{"id":"9zw05ixl9qgo00p9","createdAt":"2024-10-28T03:07:14.073Z","name":"2024-10-27 22-07-13 1.png.webp","type":"image/webp","md5":"948492f42953c2da130e239ad5106b59","size":680294,"isSensitive":true,"blurhash":"eCF=gl-n-:_3R%9bxb4.IVa#9F-qIV4.t7?axuNGR*oe~pt6M{s;WB","properties":{"width":1219,"height":955},"url":"https://mi.yumechi.jp/files/c9fa60c3-de26-4bf7-bd2a-7cab90aa310d","thumbnailUrl":"https://mi.yumechi.jp/files/thumbnail-95b7b467-9a62-47cf-8ecc-770f3097dbde","comment":null,"folderId":null,"folder":null,"userId":"9vaew1esmfme0001","user":null}],"replyId":null,"renoteId":null,"clippedCount":0},"reaction":{"id":"9zxadlurqq0h005y","user":{"id":"9zt53enb13b80l86","name":"ゆめち :role_blobcat:","username":"yumechi","host":"misskey.flowers","avatarUrl":"https://mi.yumechi.jp/proxy/avatar.webp?url=https%3A%2F%2Fs3.misskeyflowersusercontent.jp%2Fmedia%2F697ff36e-3647-4524-bc7f-5e9dcc463756.webp&avatar=1","avatarBlurhash":"e9GuRI02rUcu9v17O[GIx]%M.T-U_3-;VX~pgjX9ngI=$xkrE1f,?H","avatarDecorations":[],"isBot":false,"isCat":false,"instance":{"name":"はなみすきー","softwareName":"misskey","softwareVersion":"2024.10.1-hanami.8dcdc06d5","iconUrl":"https://static-assets.misskey.flowers/brand-assets/icons/app_v1_192x192.png","faviconUrl":"https://static-assets.misskey.flowers/brand-assets/icons/general_v1_192x192.png","themeColor":"#fd709a"},"emojis":{"role_blobcat":"https://s3.misskeyflowersusercontent.jp/media/72522002-804b-4f3b-92dd-ce8ca4b30a12.webp","ablobcatblinkhyper":"https://s3.misskeyflowersusercontent.jp/media/1eeaf1a1-9a13-4bc8-8567-f439e83ac2b3.apng"},"onlineStatus":"unknown"},"reaction":":take_it_easy@misskey.flowers:"}}}
```

</details>

## Why

1. ReactionのHookはFrontendオプションあるけど実は実装していない
2. Test HookのPayloadは実のPayloadが一致しない ユーザー/開発者は[間違えて](https://github.com/eternal-flame-AD/gotify-webhook-misskey/commit/7a93227061419796922c773e770e43cc8d7b6de5)困るかも

## Additional info (optional)

## Checklist
- [X] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [X] Test working in a local environment
- [ ] (Not needed) Add story of storybook
- [ ] Update CHANGELOG.md (スペースが無い？）
- [X] Add tests

2024-10-29 00:49 UTC, eternal-flame-AD commented on packages/backend/src/core/WebhookTestService.ts
> +			   Packed<'UserWebhookNoteBody'> |
packedUserWebhookBodySchema (oneOf) `Packed<'UserWebhookBody'>` を使うと `contents`が  何故か`any` になります

2024-11-11 13:29 UTC, samunohito requested changes
@eternal-flame-AD
何点かコメントしました。ご確認願います。

2024-11-11 13:29 UTC, samunohito commented on packages/backend/src/core/ReactionService.ts
> +			});
実装ありがとうございます。
しかし、リアクション受信時のWebhook送信については今回のprからは除いて頂きたいです（せっかく実装いただいたのにごめんなさい）

実装する前に、

- リアクション受信時にWebhookを送信するのは負荷の観点から現実的か
- 過去に廃止したが設定画面の項目を消し忘れた等の経緯が無いか

を別issueにて確認する必要があるかと思います。

2024-11-11 13:29 UTC, samunohito commented on packages/backend/src/models/json-schema/user-webhook.ts
型定義の作成、ありがとうございます。

json-schemaはバックエンド・フロントエンドの間で使用されるWebAPIの定義を用意する場所です。
これらの定義はmisskey-jsに取り込まれ、OpenAPI形式の成果物として加工されます。

WebhookのペイロードそのものはOpenAPIに掲載することはないと思われますので、TypeScriptのtype宣言で十分かと考えます。

2024-11-11 13:49 UTC, Sayamame-beans commented on packages/backend/src/core/ReactionService.ts
> +			});
related: #9485 #13393

2024-11-11 18:19 UTC, eternal-flame-AD commented on packages/backend/src/core/ReactionService.ts
> +			});
分かりました、除いてします。UIがオプションがある上に　#9485　をBugにしてタッグしたので実装したいと思いました。

サーバーの負荷方面はWebhookがapi rate limiterに記入するとかのは良いと思います？（詳しくは深く考えて別々に起票します。

2024-11-11 23:46 UTC, samunohito requested changes
コメントの反映ありがとうございました。
チェックしていたら気になる個所を見つけたので、追加でコメントさせてください。

2024-11-11 23:46 UTC, samunohito commented on packages/backend/src/core/WebhookTestService.ts
> +				send({ user: toPackedUserDetailedNotMe(dummyUser2) });
followedイベントの時はPacked<'UserLite'>になっていると思います。
理由として…userEntityService.pack()のオプションでスキーマを指定しない場合、UserLiteがデフォルト値として使用されるからです。

https://github.com/misskey-dev/misskey/blob/ff47fef5725ba31efc7016534c2d9db8b0ad242a/packages/backend/src/core/UserFollowingService.ts#L348-L357

2024-11-11 23:46 UTC, samunohito commented on packages/backend/src/core/WebhookTestService.ts
> +				send({ user: toPackedUserDetailedNotMe(dummyUser2) });
なぜここだけUserLiteなのか…という議論が別途必要だと思いますが、このままだとfollowedのペイロードが乖離してしまうので、合わせていただけると幸いです。

2024-11-11 23:56 UTC, samunohito commented on packages/backend/src/core/ReactionService.ts
> +			});
> サーバーの負荷方面はWebhookがapi rate limiterに記入するとかのは良いと思います？（詳しくは深く考えて別々に起票します。

参考までに：
https://github.com/misskey-dev/misskey/issues/9485#issuecomment-2469233258 でロール機能による制御が提案されています。

2024-11-12 00:50 UTC, samunohito approved these changes
👍

2024-11-12 00:51 UTC, merged

2024-11-12 00:51 UTC, syuilo commented
🙏