Feat: 特定ユーザーからのリアクションをブロックする機能の追加
misskey-dev/misskey pull request #14986
Opened 2024-11-17 13:20 UTC by sakuhanight

- BlockingReactionUserエンティティの追加
- blocking-reaction-userエンドポイントの追加
- 関連するフロントエンドの追加
Migrationがあります。

## What
特定ユーザーからのリアクションをブロックする

## Why
脈絡がなかったりよくわからん絵文字でリアクションをする人からリアクションを受け取りたくないが、ブロックまではする必要がないことがある。

## Additional info (optional)

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2024-11-17 13:56 UTC, kakkokari-gtyih requested changes
- ja-JP以外の翻訳ファイルはCrowdin以外から編集すると不整合が起きるため、ja-JP以外の翻訳の変更はすべて取り消してください
- lint / code styleの修正を行ってください（見つけた分だけ下に足れ下げておきます）
- ユーザーエンティティ関連のbackend testのスキーマが変更に追従していません。適切に修正してください
- BlockingReactionUserのjson schema（`/src/models/json-schema`内）が定義されていないにもかかわらず`Packed<'BlockingReactionUser'>`が使用されています。スキーマを作成して適切にインポートしたうえで使用するようにしてください
- ↑をやったうえで`pnpm build-misskey-js-with-types` を再度実行してください（misskey-jsのautogen配下は自動生成なので手動で変更しないでください）

2024-11-17 13:56 UTC, kakkokari-gtyih commented on packages/backend/src/postgres.ts
> +import {MiBlockingReactionUser} from "@/models/_.js";
```suggestion
import { MiBlockingReactionUser } from '@/models/_.js';
```

lint / code style

2024-11-17 13:56 UTC, kakkokari-gtyih commented on packages/backend/src/server/api/endpoints/blocking-reaction-user/create.ts
> +import {BlockingReactionUserService} from "@/core/BlockingReactionUserService.js";
```suggestion
import { BlockingReactionUserService } from '@/core/BlockingReactionUserService.js';
```

lint / code style

2024-11-17 13:56 UTC, kakkokari-gtyih commented on packages/backend/src/core/BlockingReactionUserService.ts
> +import {MiBlockingReactionUser} from "@/models/_.js";
```suggestion
import type { MiBlockingReactionUser } from '@/models/_.js';
```

lint / code style

2024-11-17 13:59 UTC, kakkokari-gtyih commented on packages/backend/src/core/BlockingReactionUserService.ts
> +		} as MiBlockingReactionUser;
```suggestion
		} satisfies MiBlockingReactionUser;
```

2024-11-17 14:05 UTC, kakkokari-gtyih commented on packages/backend/src/core/entities/BlockingReactionUserEntityService.ts
> +import { MiBlockingReactionUser } from '@/models/BlockingReactionUser.js';
```suggestion
import type { MiBlockingReactionUser } from '@/models/BlockingReactionUser.js';
```

2024-11-17 14:05 UTC, kakkokari-gtyih commented on packages/backend/src/server/api/endpoints/blocking-reaction-user/delete.ts
> +import type {UsersRepository, BlockingsRepository, BlockingReactionUsersRepository} from '@/models/_.js';
```suggestion
import type { UsersRepository, BlockingsRepository, BlockingReactionUsersRepository } from '@/models/_.js';
```

lint

2024-11-17 14:31 UTC, syuilo commented
新しいテーブルを作るより、既存のBlockingテーブルにカラムを追加する方がシンプルになりそうな気がしました

2024-11-17 22:03 UTC, samunohito commented on packages/backend/src/core/BlockingReactionUserService.ts
> +		blocking.blockee = blockee;
上記の処理は不要に見受けられるのですが、いかがでしょうか。
これ以降、blockingはidしか使われていないようです。

2024-11-18 00:07 UTC, sakuhanight commented
> 新しいテーブルを作るより、既存のBlockingテーブルにカラムを追加する方がシンプルになりそうな気がしました

既存箇所の変更を嫌ってテーブルを作成しましたが、たしかにカラム追加のほうがシンプルになる気がします。
カラム追加での変更を作成、指摘頂いた箇所を修正し、改めてPR出させてもらおうと思います。
レビューありがとうございました。

2024-11-18 06:50 UTC, closed without merging