サロゲートペアを字数にカウントしないようにする
misskey-dev/misskey pull request #2661
Opened 2018-09-07 16:46 UTC by acid-chicken

*要検討*

2018-09-07 22:10 UTC, AyaMorisawa commented
Misskeyのpackage.json見たらstringzパッケージが入ってたので、
```js
import { length } from 'stringz';
```
して、
```js
length(text.trim()); // instead of [...text.trim()].length
```
と書ける

2018-09-09 23:59 UTC, acid-chicken commented
@AyaMorisawa Done!

2018-09-10 00:06 UTC, AyaMorisawa requested changes

2018-09-10 00:06 UTC, AyaMorisawa commented on src/client/app/desktop/views/components/post-form.vue
> +impprt { length } from 'stringz';
`impprt` ???

2018-09-10 00:22 UTC, AyaMorisawa requested changes

2018-09-10 08:48 UTC, syuilo requested changes

2018-09-10 08:48 UTC, syuilo commented on src/client/app/desktop/views/components/post-form.vue
> +		}
コロンが必要そう

2018-09-10 08:48 UTC, syuilo commented on src/client/app/mobile/views/components/post-form.vue
> +		}
コロンが必要そう

2018-09-10 09:02 UTC, merged

2018-09-10 09:02 UTC, syuilo commented
ありがとうございます！