New Crowdin translations
misskey-dev/misskey pull request #3255
Opened 2018-11-15 20:41 UTC by syuilo

Enjoy!

2018-11-16 00:18 UTC, acid-chicken approved these changes

2018-11-17 12:07 UTC, acid-chicken requested changes

2018-11-17 12:07 UTC, acid-chicken commented on locales/zh-CN.yml
> +  description: "当您用Discard连接Misskey账户后，您将能够看到有关您自己的信息，并且您将能够使用Discard登录。"
DiscordがDiscardになってしまっている。

2018-11-18 01:50 UTC, Never2333 commented on locales/zh-CN.yml
> +  description: "当您用Discard连接Misskey账户后，您将能够看到有关您自己的信息，并且您将能够使用Discard登录。"
Sorry

2018-11-18 01:55 UTC, syuilo commented on locales/zh-CN.yml
> +  description: "当您用Discard连接Misskey账户后，您将能够看到有关您自己的信息，并且您将能够使用Discard登录。"
Fixed. I will merge this translations soon! thank you so much 🙏🙏🙏

2018-11-18 01:56 UTC, merged