Use for-of instead of forEach
misskey-dev/misskey pull request #3583
Opened 2018-12-10 13:52 UTC by AyaMorisawa

Co-authored-by: syuilo <syuilotan@yahoo.co.jp>
Co-authored-by: Acid Chicken (硫酸鶏) <root@acid-chicken.com>

2018-12-10 13:53 UTC, AyaMorisawa commented
Close #2501

2018-12-10 13:58 UTC, syuilo submitted a review, later dismissed

2018-12-10 13:58 UTC, syuilo commented on src/client/app/common/define-widget.ts
> +					for (const prop of Object.keys(defaultProps).filter(this.props.hasOwnProperty)) {
条件が逆転してます

2018-12-10 14:17 UTC, acid-chicken requested changes

2018-12-10 14:17 UTC, acid-chicken commented on src/client/app/mobile/views/pages/user/home.photos.vue
> +				for (const media of note.media.filter(this.images.length < 9)) {
`this.images`は中身がイミュータブルでないため、意味合いが変わっている可能性がある。

2018-12-10 14:17 UTC, acid-chicken commented on src/server/api/endpoints/users/get_frequently_replied_users.ts
> +	}
`for`自体使わない方が良さそう。

2018-12-10 14:30 UTC, AyaMorisawa commented on src/client/app/mobile/views/pages/user/home.photos.vue
> +				for (const media of note.media.filter(this.images.length < 9)) {
そもそもfilterに関数でないものを渡してますね

2018-12-10 14:30 UTC, acid-chicken approved these changes

2018-12-10 14:38 UTC, syuilo approved these changes

2018-12-10 14:43 UTC, acid-chicken commented on src/client/app/mobile/views/pages/user/home.photos.vue
> +				for (const media of note.media.filter(this.images.length < 9)) {
危ない危ない……

2018-12-10 14:58 UTC, AyaMorisawa commented on src/client/app/admin/views/emoji.vue
> +				for (const e of emojis) {
これfor無しで実現できますか

2018-12-10 14:58 UTC, AyaMorisawa commented on src/client/app/common/define-widget.ts
> +					for (const prop of Object.keys(defaultProps).filter(x => !this.props.hasOwnProperty(x))) {
`this.props`がループ内で変更されないことは保証されますか？

2018-12-10 15:38 UTC, acid-chicken commented on src/client/app/admin/views/emoji.vue
> +				for (const e of emojis) {
```ts
this.emojis = emojis.map(e => Object.assign(e, { aliases: (e.aliases || []).join(' ') }));
```
とか？

2018-12-10 19:40 UTC, syuilo commented on src/client/app/common/define-widget.ts
> +					for (const prop of Object.keys(defaultProps).filter(x => !this.props.hasOwnProperty(x))) {
ループ内で変更されますね

2018-12-11 07:16 UTC, AyaMorisawa commented on src/client/app/admin/views/emoji.vue
> +				for (const e of emojis) {
forありのままにしておきましょう

2018-12-11 07:20 UTC, AyaMorisawa commented
PTAL :)

2018-12-11 11:22 UTC, syuilo commented on src/client/app/common/define-widget.ts
> +						if (this.bakeProps.hasOwnProperty(prop)) continue;
bakePropsはメソッドではありませんか？

2018-12-11 11:33 UTC, acid-chicken approved these changes

2018-12-11 11:36 UTC, syuilo approved these changes
LGTM

2018-12-11 11:36 UTC, merged