Feed
misskey-dev/misskey pull request #3698
Opened 2018-12-20 10:30 UTC by acid-chicken

# Summary

Resolve #1509
Resolve #3689

2018-12-20 11:07 UTC, syuilo commented on src/server/web/feed.ts
> +		link: `${config.scheme}://${config.host}/@${user.username}`,
config.url で良さそう

2018-12-20 11:07 UTC, mei23 submitted a review, later dismissed
とりあえず、古い順に出てくるのと全件出力されちゃうのをどうにかしないといけないわ。

2018-12-20 11:34 UTC, syuilo commented on src/server/web/index.ts
> +	return user && await packFeed(user);
意図がわかりにくいかも

2018-12-20 11:34 UTC, mei23 requested changes

2018-12-20 11:34 UTC, mei23 commented on src/server/web/feed.ts
> +			description: note.text,
descriptionはsummaryにマップされちゃうので
```
description: note.cw,
content: note.text,
```
にしたほうがと思う

2018-12-20 11:34 UTC, mei23 commented on src/server/web/feed.ts
> +	});
件数制限がない、古い順に出てきてしまう
```
, {
    limit: 20,
    sort: { _id: -1 }
}
```
など必要

2018-12-20 11:34 UTC, mei23 commented on src/server/web/index.ts
> +		ctx.set('Content-Type', 'application/atom+xml');
`application/atom+xml; charset=utf-8`の方がいいかも

2018-12-20 11:34 UTC, mei23 commented on src/server/web/index.ts
> +		ctx.set('Content-Type', 'application/rss+xml');
`application/rss+xml; charset=utf-8`の方がいいかも

2018-12-20 11:34 UTC, mei23 commented on src/server/web/index.ts
> +		ctx.set('Content-Type', 'application/json');
`application/json; charset=utf-8`の方がいいかも

2018-12-20 11:37 UTC, acid-chicken commented on src/server/web/index.ts
> +	return user && await packFeed(user);
```ts
return user == undefined ? await packFeed(user) : undefined;
```
と書くのが冗長に感じたため。

2018-12-20 11:49 UTC, mei23 reviewed
たぶん大丈夫だと思います。
Mastodonのそれと比べると大分項目は少ないけど、最新の投稿を取得が出来ればまあ大丈夫なのではと。

以下のあたりはしたいという話が出てくるかも
- nextでページング
- 引用投稿対応

2018-12-20 11:49 UTC, mei23 approved these changes

2018-12-20 15:00 UTC, syuilo approved these changes

2018-12-21 02:36 UTC, AyaMorisawa approved these changes

2018-12-21 02:54 UTC, merged