CWの中のサムネイルのサイズが変なのを修正
misskey-dev/misskey pull request #5339
Opened 2019-08-23 20:56 UTC by mei23

## Summary
Fix #5338

ただ`for Safari bug`とあるので
SafariでCWの中にサムネイルがある場合の挙動がわからない

2019-08-23 22:57 UTC, acid-chicken commented
Safari だと見えなくなったはずなので、`'netscape' in window` とかでひとまずお茶を濁しておいてほしい感じがあります。

2019-08-24 00:19 UTC, acid-chicken requested changes
やっぱり見えなかったです。

2019-08-24 01:35 UTC, mei23 commented
'netscape' in window とは？

2019-08-24 02:37 UTC, mei23 commented
表示しないとサイズが決まらないので、CWの中だとやっぱり決め打ちするしかなくて
決め打ちをちょっと丁寧にしました。

2019-08-24 07:36 UTC, acid-chicken commented
決め打ちが発動するのが Safari と Firefox と認識していたので、`'netscape' in window` で Firefox に救済マッチを与えてみる感じです。

2019-08-24 07:38 UTC, acid-chicken approved these changes
決め打ちサイズが Safari 的にもよくなるのはいいことだと思います。

2019-08-24 10:20 UTC, syuilo commented
皆様ありがとうございます。根本的に解決できる方法があればいいんですけどね🥴

2019-08-24 10:20 UTC, merged