Assign URL to each page of settings
misskey-dev/misskey pull request #5349
Opened 2019-08-27 15:46 UTC by AyaMorisawa

## Summary
Resolve #4036

2019-08-27 15:48 UTC, acid-chicken approved these changes

2019-08-27 16:06 UTC, rinsuki requested changes

2019-08-27 16:06 UTC, rinsuki commented on src/client/app/desktop/views/components/settings.vue
> +		<p :class="{ active: page == 'other' }" @mousedown="go('other')"><fa icon="cogs" fixed-width/>{{ $t('@._settings.other') }}</p>
特別な理由がないなら、ここら一帯リンクのほうが良いと思います

2019-08-27 23:11 UTC, rinsuki commented on src/client/app/desktop/views/components/settings.vue
> +		<router-link to="/i/settings/other" @click.native="page = 'other'" :class="{ active: page == 'other' }"><fa icon="cogs" fixed-width/>{{ $t('@._settings.other') }}</router-link>
routerから振ってくる`:page`と`data.page`でデータ被ってるのがちょっと気になるので、できればrouterからの`:page`に統一したい

2019-08-27 23:11 UTC, rinsuki commented on src/client/app/desktop/views/components/settings.vue
> +		<router-link to="/i/settings/other" @click.native="page = 'other'" :class="{ active: page == 'other' }"><fa icon="cogs" fixed-width/>{{ $t('@._settings.other') }}</router-link>
https://router.vuejs.org/ja/api/#active-class 使えそう

2019-08-28 08:55 UTC, AyaMorisawa commented on src/client/app/desktop/views/components/settings.vue
> +		<router-link to="/i/settings/other" @click.native="page = 'other'" :class="{ active: page == 'other' }"><fa icon="cogs" fixed-width/>{{ $t('@._settings.other') }}</router-link>
active-class を使うには、 `i/settings` を `i/settings/profile` にリダイレクトする必要がある

2019-08-28 20:27 UTC, syuilo commented
i/settings/profile 等にいる状態でモバイル版に切り替えると not found になるのが気になります

2019-08-28 20:29 UTC, syuilo commented on src/client/app/desktop/views/components/settings.vue
> +		<p :class="{ active: page == 'other' }" @mousedown="go('other')"><fa icon="cogs" fixed-width/>{{ $t('@._settings.other') }}</p>
わざわざこうした理由としては、設定画面をウィンドウとして開いた時のためなんですが、現在設定をアプリ内ウィンドウとして開くことはないのでリンクでもいいかも

2019-08-28 20:30 UTC, syuilo commented on src/client/app/desktop/views/components/settings.vue
> +		<router-link to="/i/settings/other" @click.native="page = 'other'" :class="{ active: page == 'other' }"><fa icon="cogs" fixed-width/>{{ $t('@._settings.other') }}</router-link>
リダイレクトでいいと思います

2019-08-28 20:31 UTC, AyaMorisawa commented
モバイル版は i/settings にリダイレクトしますか？

2019-08-28 20:32 UTC, syuilo commented
それで良いと思います

2019-08-28 20:45 UTC, syuilo approved these changes

2019-08-28 23:20 UTC, rinsuki approved these changes

2019-08-29 05:57 UTC, merged

2019-08-29 05:57 UTC, syuilo commented
👍🥰👍