Preserve the attached order in AP
misskey-dev/misskey pull request #5561
Opened 2019-10-28 20:54 UTC by mei23

## Summary
Fix: #5550, Fix: #5558

APでNoteの添付ファイルを提示する時に添付順を保持するように

2019-10-28 21:37 UTC, rinsuki requested changes

2019-10-28 21:37 UTC, rinsuki commented on src/remote/activitypub/renderer/note.ts
> +	const files = (await Promise.all((note.fileIds || []).map(x => DriveFiles.findOne(x)))).filter(x => x != null) as DriveFile[];
添付ファイルの数だけクエリが発行されるのあまりよろしくない気がする。
https://github.com/syuilo/misskey/issues/5558#issuecomment-546859849 にあったように、今まで通りInで取って、その後こっち側で本来期待した順に並び換えるほうが良いと思う。

2019-10-28 21:47 UTC, mei23 commented on src/remote/activitypub/renderer/note.ts
> +	const files = (await Promise.all((note.fileIds || []).map(x => DriveFiles.findOne(x)))).filter(x => x != null) as DriveFile[];
キャッシュできないAPIのドライブファイルの解決でガンガンPromise.allしてるくらいなので
Push時に1回 or Pullでもリクエスト自体キャッシュ可能なAPのRenderでそこまで気にしなくていいかなって思いました

2019-10-28 22:05 UTC, rinsuki commented on src/remote/activitypub/renderer/note.ts
> +	const files = (await Promise.all((note.fileIds || []).map(x => DriveFiles.findOne(x)))).filter(x => x != null) as DriveFile[];
私的には「もっとよくないコードがある」は(特別な他の事情がない限り)通す理由にはならないと思うけど、この類の話は2人で話してもらちがあかなくなりそうなので他のレビュワーに判断を任せる

2019-10-28 22:20 UTC, mei23 commented on src/remote/activitypub/renderer/note.ts
> +	const files = (await Promise.all((note.fileIds || []).map(x => DriveFiles.findOne(x)))).filter(x => x != null) as DriveFile[];
DBクエリのPromise.allの類はv10 (mongodb) では結構余裕 (mongodbの接続数制限は大分緩い) だったので、v11でも結構残ってるんですが
これ系結構あるように思えるのでパフォーマンス的に問題があるようなら別途Isseueとして対応するというのもありかと思います

2019-10-28 23:04 UTC, mei23 commented on src/remote/activitypub/renderer/note.ts
> +	const files = (await Promise.all((note.fileIds || []).map(x => DriveFiles.findOne(x)))).filter(x => x != null) as DriveFile[];
備忘
```ts
	const promisedFiles = async () => {
		if (!note.fileIds || note.fileIds.length === 0) return [];
		const items = await DriveFiles.find({ id: In(note.fileIds) });
		return note.fileIds.map(id => items.find(item => item.id === id)).filter(item => item != null) as DriveFile[];
	};
```

2019-10-28 23:54 UTC, mei23 commented on src/remote/activitypub/renderer/note.ts
> +	const files = (await Promise.all((note.fileIds || []).map(x => DriveFiles.findOne(x)))).filter(x => x != null) as DriveFile[];
(APIの方は後々修正されると期待して)
> 今まで通りInで取って、その後こっち側で本来期待した順に並び換えるほうが良いと思う。

にしときました

2019-10-29 00:05 UTC, mei23 commented on src/remote/activitypub/renderer/note.ts
> +	const files = (await Promise.all((note.fileIds || []).map(x => DriveFiles.findOne(x)))).filter(x => x != null) as DriveFile[];
> 私的には「もっとよくないコードがある」は(特別な他の事情がない限り)通す理由にはならないと思うけど

ここでの議論点はあくまでも添付順の順番なのでAPIと同等の順番とパフォーマンスでAP側が実装されていれば問題ないという認識

2019-10-31 13:11 UTC, rinsuki approved these changes

2019-10-31 20:46 UTC, merged

2019-10-31 20:46 UTC, syuilo commented
👍👍👍