フォロワーではないリモートユーザーに削除通知が配信されない問題を修正
misskey-dev/misskey pull request #6475
Opened 2020-06-24 14:45 UTC by mfmfuyu

## Summary
フォローされていないリモートユーザーへのメンションを含む投稿を削除すると削除通知が配信されない問題を修正しました。
Misskey(0d36b144cfea16496ee9157205ed309ce44ab918)同士、Misskey(12.39.1)とMastodon(3.1.4)で上記の問題が発生している事を確認しました。
MastodonやPleromaなどとのテストやユニットテストが不十分なので一度Draftで作成いたします。

2020-06-26 11:42 UTC, mei23 commented
メモ書き

たぶん
Create時にはフォロワーとリレーだけではなくメンションだけしたユーザーなどにも配信しているが
Delete時にはフォロワーとリレーだけにしか配信していないという問題
https://github.com/syuilo/misskey/blob/0d36b144cfea16496ee9157205ed309ce44ab918/src/services/note/create.ts#L325-L361

Createとの対応を考えると
- リプライ先にもDelete配信が必要？→mentionedRemoteUserに含まれるようになってそうなので不要かも
- Renote先にもDelete配信が必要？→必要な気がする
- フォロワーとリレーへのDelete配信の対象がCreateより広いけどいいのか？→広い部分にはいいのか…

あと、これとは直接関係ないが、カスケードNoteのDelete処理がなんかイケてない気がする。(そもそもカスケードDeleteがイケてないが…)
「DBをカスケード削除した後に、カスケードNoteを幹から先の方に辿っていきながらAP Delete配信のみ行う」ではなく
「DBのカスケード削除をする前に、カスケードNoteのツリーを全部列挙して、
枝の先のNoteから`services/note/delete`をそれぞれ呼び出す (この際はフラグなど付けてカスケード探索なし) 」
のほうが良さそうに見える。

2020-06-26 19:46 UTC, mei23 approved these changes
フォロワーの居ないインスタンスにメンション/リプライした投稿の削除が配信されない
問題自体は直ってるのと、軽くテストしたところ大丈夫だったので、~~マージしちゃっていいかなと思います~~。
→Inクエリがダメだった

2020-06-26 19:47 UTC, mei23 commented
以下の関連バグ等も見つけたけど別途でいいかなと。
- フォロワーのいないインスタンスに引用投稿のDeleteが飛ばない
- フォロワーのいないインスタンスにRenote解除 (Undo Announce) が飛ばない
- 「カスケード削除後にカスケード分のAP配信」ではなく「カスケード削除前にカスケード分をツリーの先から削除」した方がよさそう

2020-06-26 20:14 UTC, mei23 requested changes

2020-06-26 20:14 UTC, mei23 commented on src/services/note/delete.ts
> +			uri: In(mentions)
長さ0のときにQuery Errorぽい
https://github.com/syuilo/misskey/blob/develop/CONTRIBUTING.md#-in-sql

2020-06-26 20:36 UTC, mei23 commented
@mfmfuyu
https://github.com/mfmfuyu/misskey/pull/1 に以下の修正を投げたので、ご確認お願いします。
- メンションの数が0の時にクエリエラーになるのを修正
- Renote/Quote先のユーザーも対象にするように
- 不要な場合にはクエリしないように

2020-06-27 01:20 UTC, mfmfuyu commented
すみません、色々とありがとうございます。
また、確認不足で問題があったようで、すみませんでした。
頂いたPRの方を確認いたします。

2020-06-27 03:03 UTC, mfmfuyu commented
頂いたPRに関しては確認してマージを行いました。
また、1つ気になった事があるのですが下記のフォロワーとリプライ先の配信時の処理ですが、`Create`時と同じように直接`DeliverManager`を扱い`addFollowersRecipe`と`addDirectRecipe`を呼んだほうがいいですかね？（リクエスト数が減る？
https://github.com/syuilo/misskey/blob/0753e52dc1c9f00a8d986fd9f6634b543c512f6f/src/services/note/delete.ts#L130-L136

2020-06-27 03:24 UTC, mei23 commented
> 下記のフォロワーとリプライ先の配信時の処理ですが、Create時と同じように直接DeliverManagerを扱いaddFollowersRecipeとaddDirectRecipeを呼んだほうがいいですかね？（リクエスト数が減る？

1. フォロワー配信: フォロワーの`sharedInbox || inbox`群をuniqしたものに配信
2. リプライ先配信: 対象ユーザーの`inbox`に配信
で基本的に対象は被らないのでなくていいかなと思いました。

1で`sharedInbox`を持ってないフォロワーがいた場合に 2と被る可能性はあるのですが、`sharedInbox`を持ってないパターンはまずないかなと思います。
(`DeliverManager`でまとめたほうが確実ではありますが…)

2020-06-27 05:59 UTC, mfmfuyu commented
なるほど、ありがとうございます。

2020-07-04 12:08 UTC, mei23 approved these changes

2020-07-04 12:12 UTC, mei23 commented
Misskey間でも大丈夫だったのでたぶん大丈夫

2020-07-05 03:16 UTC, mfmfuyu commented
私の方でもいくつかの環境で一度テストしてみようと思います

2020-07-05 03:44 UTC, mfmfuyu commented
下記の環境でも、フォローをしている/外している状態でも削除通知が配信される事を確認しました。
 - Mastodon (08cf81f8c1b445eba9972214869c376fe6097efb)
 - Pleroma (2.0.50-1709-g7c7a6509)

2020-07-11 15:44 UTC, merged

2020-07-11 15:44 UTC, syuilo commented
お二方ありがとうございます🥰🥰🥰