Password reset
misskey-dev/misskey pull request #7494
Opened 2021-05-02 15:44 UTC by syuilo

## Summary

Resolve #1847

2021-05-02 16:25 UTC, YuzuRyo61 requested changes
指定されたメールが見つからなかった時のエラーが適切に処理できてないので、
見つからなくても成功したという振る舞いをするべきだと思う

2021-05-02 16:25 UTC, YuzuRyo61 commented on src/server/api/endpoints/request-reset-password.ts
> +	const profile = await UserProfiles.findOneOrFail({
レコードが見つかった、見つからなかったどちらの場合でもHTTP 200を返しておくべきだと思う
（今の状態だと見つからなかった場合は500が返ってくる）

2021-05-02 17:03 UTC, mei23 commented on src/server/api/endpoints/request-reset-password.ts
> +	});
そもそも、`UserProfile.email`にはunique制約付いてないのでそれだけで選択しちゃダメなはず。
ユーザーに`usernaname`を一緒に入力させて、そのユーザーに紐づくメールアドレスのみ対象にするとかする必要がある。

2021-05-02 17:13 UTC, mei23 commented on src/server/api/endpoints/request-reset-password.ts
> +	});
または、`usernaname`のみを入力させるでもいい？

2021-05-02 17:25 UTC, mei23 commented
あと、tokenの期限チェックがほしい。

2021-05-03 02:50 UTC, syuilo commented on src/server/api/endpoints/request-reset-password.ts
> +	});
GitHubの場合ユーザー名じゃなくてメアド入力させられるから、何か理由あるのかなと思った
どっちも入力させよう

2021-05-03 03:57 UTC, syuilo commented
- ユーザー名も入力させるようにした
- 期限チェック実装した

2021-05-03 05:15 UTC, syuilo commented
- エラーハンドリング直した

2021-05-03 05:16 UTC, syuilo commented
@YuzuRyo61 @mei23 確認お願いします

2021-05-03 05:35 UTC, YuzuRyo61 approved these changes

2021-05-03 05:42 UTC, mei23 commented on src/server/api/endpoints/request-reset-password.ts
> +	});
同じemailが複数のユーザーで使われている可能性があるので、これだとどれか1つのユーザーしか選ばれないと思います。
先に `Users.usernameLower` を照合するか、表結合でまとめて照合する必要があると思います。

2021-05-03 05:48 UTC, mei23 commented on src/server/api/endpoints/reset-password.ts
> +	// 発行してから3分以上経過していたら無効
メール配送→URLにアクセス→パスワード入力 まで3分はちょっと短いかも？
たいてい1時間は猶予があるみたいです。

2021-05-03 05:49 UTC, mei23 commented on src/server/api/endpoints/request-reset-password.ts
> +	},
未認証時にはlimitを定義しても使われないみたいです

2021-05-03 05:49 UTC, syuilo commented on src/server/api/endpoints/request-reset-password.ts
> +	},
将来的に何らかの方法で非ログインでもリミットかけられるようになる可能性に期待して設定してみた

2021-05-03 05:49 UTC, syuilo commented on src/server/api/endpoints/request-reset-password.ts
> +	},
↑IPアドレスとかで

2021-05-04 05:09 UTC, syuilo commented
- 期限を3分→30分に
- 同じemailが複数のユーザーで使われている場合の対応

2021-05-04 06:00 UTC, mei23 approved these changes
コード見た感じは多分大丈夫

2021-05-04 06:05 UTC, merged

2021-05-04 06:05 UTC, syuilo commented
🙏🙏🙏