歓迎ページでバナー画像が表示されない問題を修正
misskey-dev/misskey pull request #7559
Opened 2021-06-05 17:12 UTC by noridev

## Summary

Resolve #7558

2021-06-06 23:31 UTC, rinsuki requested changes
bannerUrl は /explore とかで使われる用なので kanban とかで使うべきではなくて、どちらかというと backgroundImageUrl が設定できないほうがバグなはず

2021-06-07 06:42 UTC, noridev commented
抜けた設定オプションを追加することで変更

2021-06-07 15:20 UTC, rinsuki approved these changes

2021-06-08 03:17 UTC, merged

2021-06-08 03:17 UTC, syuilo commented
🙏