fix(#8133): hCaptcha の reCAPTCHA 互換挙動を無効化する
misskey-dev/misskey pull request #8135
Opened 2022-01-10 15:19 UTC by acid-chicken

# What

hCaptcha をロードしても reCAPTCHA (v2) が死なないようにする

# Why

Fixes #8133

# Additional info (optional)

2022-01-10 15:35 UTC, tamaina requested changes

2022-01-10 15:35 UTC, tamaina commented on packages/client/src/components/captcha.vue
> +		case 'hcaptcha': return 'https://hcaptcha.com/1/api.js?render=explicit&recaptchacompat=off'
```suggestion
		case 'hcaptcha': return 'https://hcaptcha.com/1/api.js?render=explicit&recaptchacompat=off';
```

2022-01-18 14:39 UTC, tamaina approved these changes

2022-01-21 08:43 UTC, merged

2022-01-21 08:43 UTC, syuilo commented
🙏🙏🙏