Refactor custom-css to use Composition API
misskey-dev/misskey pull request #8571
Opened 2022-04-29 22:56 UTC by pixeldesu

# What

Use Composition API for `settings/custom-css` page

# Why

Refactor to Composition API (per contribution guide)

2022-04-30 19:08 UTC, Johann150 requested changes

2022-04-30 19:08 UTC, Johann150 commented on packages/client/src/pages/settings/custom-css.vue
> +const localCustomCss = ref(localStorage.getItem('customCss') ?? '');
nice catch with the `??` 👍

2022-04-30 19:08 UTC, Johann150 commented on packages/client/src/pages/settings/custom-css.vue
> +	apply();
```suggestion
	await apply();
```

2022-04-30 19:22 UTC, Johann150 approved these changes

2022-05-01 06:50 UTC, merged

2022-05-01 06:50 UTC, syuilo commented
🙏