Refactor settings/menu to use Composition API
misskey-dev/misskey pull request #8586
Opened 2022-05-01 12:30 UTC by pixeldesu

# What

Use Composition API for `settings/menu` page

# Why

Refactor to Composition API (per contribution guide)

# Additional info (optional)

The `reloadAsk()` method present here is exactly the same as in `settings/general`, once both this PR and #8578 have been merged, I will split out the method into it's own script that can be referenced in both places.

2022-05-01 13:13 UTC, Johann150 requested changes

2022-05-01 13:13 UTC, Johann150 commented on packages/client/src/pages/settings/menu.vue
> +}
you already `await` save later, but it is not defined as async

```suggestion
async function save() {
	defaultStore.set('menu', split.value);
	await reloadAsk();
}
```

2022-05-01 13:13 UTC, Johann150 commented on packages/client/src/pages/settings/menu.vue
> +		}]]
```suggestion
		})), {
			value: '-', text: i18n.ts.divider
		}]
```

2022-05-01 13:35 UTC, Johann150 approved these changes

2022-05-04 01:12 UTC, merged

2022-05-04 01:12 UTC, syuilo commented
🙏