Improve README
misskey-dev/misskey pull request #8645
Opened 2022-05-10 22:18 UTC by ThatOneCalculator

# What

- Cleaner floating logo
- Use uniform badges
- Use text from Misskey-hub

# Why

To keep readme more in line with Misskey-hub

2022-05-11 07:39 UTC, syuilo commented
- The animated logo has its pros and cons, but I thought it was funny.
- The badges were colorful, eye-catching, and I loved them.

2022-05-11 19:13 UTC, Johann150 requested changes
You added alt text to the first image, but then didn't add alt text to the other ones.

I'm also not totally convinced of the phrasing. Please note: I did not review <https://github.com/misskey-dev/misskey-hub/pull/81> so the same might apply to there.

2022-05-11 19:13 UTC, Johann150 commented on README.md
> +		<img src="https://custom-icon-badges.herokuapp.com/badge/find_an-instance-acea31?logoColor=acea31&style=for-the-badge&logo=misskey&labelColor=363B40" /></a>
```suggestion
		<img src="https://custom-icon-badges.herokuapp.com/badge/find_an-instance-acea31?logoColor=acea31&style=for-the-badge&logo=misskey&labelColor=363B40" alt="find an instance"/></a>	
```

2022-05-11 19:13 UTC, Johann150 commented on README.md
> +		<img src="https://custom-icon-badges.herokuapp.com/badge/create_an-instance-FBD53C?logoColor=FBD53C&style=for-the-badge&logo=server&labelColor=363B40" /></a>
```suggestion
		<img src="https://custom-icon-badges.herokuapp.com/badge/create_an-instance-FBD53C?logoColor=FBD53C&style=for-the-badge&logo=server&labelColor=363B40" alt="create an instance"/></a>	
```

2022-05-11 19:13 UTC, Johann150 commented on README.md
> +		<img src="https://custom-icon-badges.herokuapp.com/badge/become_a-contributor-A371F7?logoColor=A371F7&style=for-the-badge&logo=git-merge&labelColor=363B40"/>
```suggestion
		<img src="https://custom-icon-badges.herokuapp.com/badge/become_a-contributor-A371F7?logoColor=A371F7&style=for-the-badge&logo=git-merge&labelColor=363B40" alt="become a contributor"/>
```

2022-05-11 19:13 UTC, Johann150 commented on README.md
> +		<img src="https://custom-icon-badges.herokuapp.com/badge/join_the-community-5865F2?logoColor=5865F2&style=for-the-badge&logo=discord&labelColor=363B40"/>
```suggestion
		<img src="https://custom-icon-badges.herokuapp.com/badge/join_the-community-5865F2?logoColor=5865F2&style=for-the-badge&logo=discord&labelColor=363B40" alt="join the community"/>
```

2022-05-11 19:13 UTC, Johann150 commented on README.md
> +		<img src="https://custom-icon-badges.herokuapp.com/badge/become_a-patron-F96854?logoColor=F96854&style=for-the-badge&logo=patreon&labelColor=363B40" />
```suggestion
		<img src="https://custom-icon-badges.herokuapp.com/badge/become_a-patron-F96854?logoColor=F96854&style=for-the-badge&logo=patreon&labelColor=363B40" alt="become a patron"/>
```

2022-05-11 19:13 UTC, Johann150 commented on README.md
> +Not on Misskey? No problem! Not only can Misskey instances talk each other, but you can make friends with people on other networks like Mastodon and Pixelfed!
```suggestion
Not on Misskey? No problem! Not only can Misskey instances talk to each other, but you can make friends with people on other networks like Mastodon and Pixelfed!
```

2022-05-11 19:13 UTC, Johann150 commented on README.md
> +Hate not being able to find something you uploaded? With Drive, you get managed and powerful cloud storage right in your social media!
In my opinion these previous parts were fine, and the new phrasing sounds too enthusiastic.

2022-05-11 19:13 UTC, Johann150 commented on README.md
> +	Misskey has a rich and complex (but easy to use) Web UI!
"complex but easy to use" sounds very much like a contradiction. The adjective "rich" already expresses that idea so I don't think we need that strange wording.

```suggestion
	Misskey has a rich web user interface!
```

I think we could even say that Misskey has multiple web user interfaces, too.

2022-05-11 19:13 UTC, Johann150 commented on README.md
> +	It's highly customizable, from changing the layout, adding widgets and making themes.
Better not use an apostrophe in a more formal text like this. The "from" doesn't really make sense this way, maybe something like:
```suggestion
	It is highly customizable, from changing the layout and adding widgets to making custom themes.
```

2022-05-11 19:13 UTC, Johann150 commented on README.md
> +- And so more...
```suggestion
- And much more...
```

2022-05-11 19:35 UTC, ThatOneCalculator commented on README.md
> +- And so more...
Yep, typo on my part

2022-05-11 19:35 UTC, ThatOneCalculator commented on README.md
> +Hate not being able to find something you uploaded? With Drive, you get managed and powerful cloud storage right in your social media!
It's still the phrasing used on the website

2022-05-11 19:36 UTC, ThatOneCalculator commented on README.md
> +	Misskey has a rich and complex (but easy to use) Web UI!
How about "Misskey has a rich, customizable, and easy to use web user interface!"

2022-05-11 19:54 UTC, Johann150 commented on README.md
> +	Misskey has a rich and complex (but easy to use) Web UI!
It already says that it is customizable on the next line down. But I could go with easy to use.

2022-05-11 19:56 UTC, ThatOneCalculator commented on README.md
> +	Misskey has a rich and complex (but easy to use) Web UI!
How about
```
	Misskey has a rich but easy to use Web UI!
	It is highly customizable, from changing the layout and adding widgets to making custom themes.
	Furthermore, plugins can be created using AiScript, an original programming language.
```

2022-05-12 09:10 UTC, Johann150 commented on README.md
> +Hate not being able to find something you uploaded? With Drive, you get managed and powerful cloud storage right in your social media!
That might be the case, but that does not change my opinion of the text. See the note above:
> Please note: I did not review https://github.com/misskey-dev/misskey-hub/pull/81 so the same might apply to there.

2022-05-13 20:53 UTC, ThatOneCalculator commented on README.md
> +Hate not being able to find something you uploaded? With Drive, you get managed and powerful cloud storage right in your social media!
@Johann150 What do you think would be better phrasing for this section?

2022-05-14 08:43 UTC, Johann150 commented on README.md
> +Hate not being able to find something you uploaded? With Drive, you get managed and powerful cloud storage right in your social media!
> In my opinion these previous parts were fine

2022-05-17 15:10 UTC, Johann150 approved these changes

2022-05-17 16:06 UTC, ThatOneCalculator commented
@syuilo seems everything's good now :)

2022-05-17 16:12 UTC, merged

2022-05-17 16:12 UTC, syuilo commented
👍👍👍