Refactor file-dialog to use Composition API
misskey-dev/misskey pull request #8661
Opened 2022-05-13 19:31 UTC by pixeldesu

# What

Use Composition API for file dialog component in the admin settings

# Why

Refactor to Composition API (per contribution guide)

2022-05-14 09:01 UTC, Johann150 requested changes

2022-05-14 09:01 UTC, Johann150 commented on packages/client/src/pages/admin/file-dialog.vue
> +});
```suggestion
const props = defineProps<{
	fileId: string,
}>();
```

2022-05-15 11:02 UTC, Johann150 approved these changes

2022-05-17 16:33 UTC, merged

2022-05-17 16:33 UTC, syuilo commented
🙏