Add guest button
misskey-dev/misskey pull request #8918
Opened 2022-07-01 06:38 UTC by ThatOneCalculator

# What
Adds a "Guest" button to the welcome page

# Why
Good way for accessing the featured page without being signed in and might entice new users to checkout the instance more.

# Additional info (optional)
![image](https://user-images.githubusercontent.com/44733677/176838477-7de4396b-9df0-4b06-bc80-849cf34cb7a7.png)

2022-07-01 21:09 UTC, Johann150 requested changes
I'm not sure why you named the button "guest" (which introduces a new internationalization string) instead of calling it just "explore" since that is where it goes to.

2022-07-01 21:09 UTC, Johann150 commented on packages/client/src/pages/welcome.entrance.a.vue
> +					<MkButton inline rounded style="margin-left: 12px;" onclick="window.location.href='/featured'">{{ i18n.ts.guest }}</MkButton>
If it is a link you can use `link` and `to` as seen in:
https://github.com/misskey-dev/misskey/blob/01d5a97a4fab5f311f977b897e779a1393c1cd05/packages/client/src/pages/my-antennas/index.vue#L5

```suggestion
					<MkButton :link="true" to="/featured" inline rounded style="margin-left: 12px;">{{ i18n.ts.guest }}</MkButton>
```

2022-07-01 21:17 UTC, ThatOneCalculator commented
> I'm not sure why you named the button "guest" (which introduces a new internationalization string) instead of calling it just "explore" since that is where it goes to.

Honestly you're right, that's just what I was calling it before on my instance's patchset.

2022-07-02 12:57 UTC, robflop commented
The purpose of this looks related to #8927.

2022-07-02 13:28 UTC, Johann150 requested changes
The `/featured` page has been removed in commit afe0d9a2663b541237a326b8dfbbb3d5070fa11f. I'm not sure what the appropriate replacement page is.

2022-07-02 20:35 UTC, ThatOneCalculator commented
It's `/explore` 

![image](https://user-images.githubusercontent.com/44733677/177015504-70a4b9b9-ae28-4879-9ebb-c5248c3c3dcf.png)

2022-07-02 21:13 UTC, Johann150 approved these changes

2022-07-03 05:13 UTC, ThatOneCalculator commented
Gonna draft this until #8927 is either merged or closed. If it's merged, I'll change `/explore` to `/timeline`.

2022-07-03 11:08 UTC, futchitwo commented
> Gonna draft this until #8927 is either merged or closed. If it's merged, I'll change `/explore` to `/timeline`.

Note that if both local and global timelines are disabled, nothing will appear on the timeline page!

2022-07-03 17:04 UTC, ThatOneCalculator commented
Ah, then maybe if both are disabled, automatically redirect it to `/explore`? Also, I'm not sure of any instances that have both disabled

2023-01-16 18:13 UTC, tamaina commented
I don't think I should close this PR.

2023-02-23 17:35 UTC, CutestNekoAqua commented
well, its implemented in calckey now, not sure if this is still up to date code?

2023-03-05 07:18 UTC, saschanaz commented
Should I open a new PR for this? Not sure why this is not being merged

2023-03-07 15:00 UTC, CutestNekoAqua commented
> Should I open a new PR for this? Not sure why this is not being merged

thats a... dumb thing to propose? wouldnt that be just copying the authors work and you getting credit for it?

2023-03-07 16:03 UTC, saschanaz commented
That was solely because this PR is currently stale. Dumb indeed if the author intends to maintain this!

2023-03-07 17:18 UTC, ThatOneCalculator commented
I don't intend to maintain this PR, and it's only one line. Do with it what you will

2023-03-10 13:34 UTC, acid-chicken commented
> > Should I open a new PR for this? Not sure why this is not being merged
>
> thats a... dumb thing to propose? wouldnt that be just copying the authors work and you getting credit for it?

I recommend learning the difference between Author and Committer in Git.

2023-03-10 13:37 UTC, saschanaz commented
(Oops, sorry for noise)

There's also a co-author thing in Git too.

2023-04-14 06:01 UTC, tamaina commented
Close due to the unlikely atmosphere of merging.

2023-04-14 06:02 UTC, closed without merging