Compress non-animated PNG files
misskey-dev/misskey pull request #9334
Opened 2022-12-17 06:24 UTC by saschanaz

Fixes #9277

# What

1. Adds a dependency `is-file-animated` that parses image header from a Blob to detect whether it's an animated image.
2. Splits compression configuration part as `compress-config.ts` from `packages/client/src/scripts/upload.ts`
3. Adds a client unit test for `compress-config.ts`, with additional setup to run Jest for client

# Why

1. To prevent losing animation by falsely compressing APNG to JPEG.
2. To write a unit test without importing everything (that depends on browser features or requires Jest transformer, e.g. Vue files)
3. To make sure nothing breaks by my bad code. I had to setup Jest myself as I couldn't find existing tests for client.

# Additional info (optional)

2022-12-17 06:39 UTC, tamaina requested changes

2022-12-17 06:39 UTC, tamaina commented on packages/client/src/scripts/upload/compress-config.ts
> +	'image/png': { quality: 0.85, mimeType: 'image/jpeg' },
pngに変換したい  
(ただしbrowser-image-resizerは元のpngよりサイズの大きいpngを吐く可能性がある

2022-12-17 06:41 UTC, tamaina commented
jest周りは分離してPRを出してください

2022-12-17 06:55 UTC, saschanaz commented on packages/client/src/scripts/upload/compress-config.ts
> +	'image/png': { quality: 0.85, mimeType: 'image/jpeg' },
Windowsでスクショとるとサイズ大きいPNGでるしもうちょっと何とかしたい感あります
でもそれは別のPRでいいかも

2022-12-17 07:09 UTC, saschanaz commented on packages/client/src/scripts/upload/compress-config.ts
> +	'image/png': { quality: 0.85, mimeType: 'image/jpeg' },
確かにjpegにするとalpha channelのこともありますね
でもそれはwebp->jpgも同じ🧐

2022-12-17 07:12 UTC, saschanaz commented on packages/client/src/scripts/upload/compress-config.ts
> +	'image/png': { quality: 0.85, mimeType: 'image/jpeg' },
どっちもwebpにすれば解決？

2022-12-17 07:35 UTC, tamaina commented
本音としてはwasm-vipsでバックエンドと同じ結果を得たいけど、SafariがSIMDに対応してないのでダメということらしい

2022-12-17 07:37 UTC, tamaina commented
PNG to PNG、サイズが大きくなってしまわないかしら

(縮小の時だけ処理するとかがいいのかも

2022-12-17 07:41 UTC, tamaina commented
しかしpngをjpegに圧縮するのは許し難い

2022-12-17 07:41 UTC, saschanaz commented
> PNG to PNG、やっぱりサイズが大きくなってしまわないかしら
> 
> (縮小の時だけ処理するとかがいいのかも

なんかややこしくなりそうですが、一斉quality 95 WebPにしたらどうですか

2022-12-17 07:44 UTC, tamaina commented
webp

- Mastodon v3が対応してない
- Safariはqualityを無視する

2022-12-17 08:10 UTC, tamaina commented
送信サイズの削減だけをねらうならいっそのことwasm-avif でavif にしちゃった方が良さそう

2022-12-17 08:26 UTC, saschanaz commented
圧縮の後のサイズチェックを追加してみました
こうしたらなぜかもっと大きくなったJPGにも対応できます

2022-12-17 08:27 UTC, tamaina commented
> 圧縮の後のサイズチェックを追加してみました
> 
> こうしたらなぜかもっと大きくなったJPGにも対応できます

良さそう

2022-12-17 12:05 UTC, tamaina commented
is-file-animatedってavif対応しないのかしら？

2022-12-17 12:11 UTC, tamaina commented
/deploy sha=dfb6ed5acfc0bc12c5d9543a9664d499eec64661

2022-12-17 12:15 UTC, tamaina commented
/deploy sha=dfb6ed5

2022-12-17 12:16 UTC, tamaina commented
/deploy sha=d1fce3664cc9cb9396643463ec3651d804bcee4e

2022-12-17 12:35 UTC, tamaina commented
圧縮前か圧縮後のどちらを使ったかをconsole.logで知りたい (if (_DEV_)で)(風呂に入るけど)

2022-12-17 13:56 UTC, saschanaz commented
もっと情報をロギングするようにしました。JPGは圧縮したら悪くなる場合が多いことが判明。 PNGは意外と悪くなかったです

2022-12-17 13:58 UTC, tamaina commented
/deploy sha=163b5e4

2022-12-17 13:58 UTC, tamaina commented
ブラウザによって圧縮率が異なるかもしれない

2022-12-17 14:11 UTC, saschanaz commented
ふむ。PNGもJPGもChromeでもうちょっと小さくなることがわかりました

どっちも圧縮したら悪くなる場合が少なくないのでこれは役に立つかも

2022-12-17 14:11 UTC, tamaina commented
…ところで: 今のままだとNODE_ENVが強制的にproductionにされてしまう

2022-12-17 14:20 UTC, tamaina commented
`vite build --mode development`しなければならないんだけど、Windows環境のことを考えるとどうにもならんような気がする

2022-12-17 14:27 UTC, saschanaz commented
> `vite build --mode development`しなければならないんだけど、Windows環境のことを考えるとどうにもならんような気がする

Windowsで `yarn dev` したらちゃんとdev modeで動きます

2022-12-17 14:32 UTC, tamaina commented
> Windowsで yarn dev したらちゃんとdev modeで動きます

yarn devはyarn build --watch --mode developmentだから…まあローカルはこれでいいのか

(okteto環境でもdevelopmentで動いて欲しいという話)

> （でもなんかbackendビルド終わってないのにbootしようとします）

通常運行

2022-12-17 14:33 UTC, tamaina commented
yarn devのvite build --watchは妥協案で、やっぱりHMRで動かしたいと思っている

2022-12-17 14:46 UTC, tamaina approved these changes

2022-12-17 14:47 UTC, tamaina commented
一応しゅいろにレビューリクエストするか

2022-12-17 15:07 UTC, tamaina commented
p1.a9z.devでテスト中

2022-12-18 06:40 UTC, merged

2022-12-18 06:40 UTC, syuilo commented
👍